const PREPOSITIONS = new Set(["da", "de", "do", "dos", "das", "e"]);

const ACCENT_MAP: Record<string, string> = {
  "joao": "João", "jose": "José",
  "goncalves": "Gonçalves", "conceicao": "Conceição",
  "sebastiao": "Sebastião",
  "andre": "André", "monica": "Mônica", "sonia": "Sônia",
  "lucia": "Lúcia", "lucio": "Lúcio", "luzia": "Lúzia",
  "mario": "Mário", "marcio": "Márcio", "marcia": "Márcia",
  "fabio": "Fábio", "sergio": "Sérgio", "rogerio": "Rogério",
  "eugenio": "Eugênio",
  "genesio": "Genésio", "jeronimo": "Jerônimo",
  "ines": "Inês", "agnes": "Agnês",
  "valeria": "Valéria", "valerio": "Valério",
  "flavia": "Flávia", "flavio": "Flávio",
  "claudia": "Cláudia", "claudio": "Cláudio",
  "alvaro": "Álvaro", "amelia": "Amélia",
  "angela": "Ângela", "angelo": "Ângelo",
  "antonio": "Antônio", "antonia": "Antônia", "araujo": "Araújo",
  "atilio": "Atílio", "aurelio": "Aurélio",
  "barbara": "Bárbara", "bras": "Brás",
  "candido": "Cândido",
  "cassio": "Cássio", "cecilia": "Cecília",
  "celia": "Célia", "celio": "Célio",
  "cesar": "César", "cintia": "Cíntia",
  "cristovao": "Cristóvão", "dario": "Dário",
  "debora": "Débora", "decio": "Décio",
  "elidia": "Elídia", "emilia": "Emília",
  "erica": "Érica",
  "fatima": "Fátima", "felicio": "Felício",
  "felix": "Félix", "ferminio": "Fermínio",
  "getulio": "Getúlio",
  "graca": "Graça", "helio": "Hélio",
  "horacio": "Horácio", "ignacio": "Ignácio",
  "inacio": "Inácio",
  "isaias": "Isaías", "januario": "Januário",
  "julio": "Júlio", "julia": "Júlia",
  "lazaro": "Lázaro",
  "lidio": "Lídio", "livio": "Lívio",
  "luisa": "Luísa",
  "macario": "Macário", "maximo": "Máximo",
  "mauricio": "Maurício", "moises": "Moisés",
  "nadia": "Nádia",
  "natalia": "Natália", "natalio": "Natálio",
  "nelio": "Nélio", "nemesio": "Nemésio",
  "otavio": "Otávio",
  "otilia": "Otília", "olimpio": "Olímpio",
  "oscar": "Óscar", "patricia": "Patrícia",
  "patricio": "Patrício",
  "placido": "Plácido", "procopio": "Procópio",
  "regia": "Régia", "regio": "Régio",
  "rosalia": "Rosália",
  "rosario": "Rosário",
  "simao": "Simão",
  "silvia": "Sílvia", "silvio": "Sílvio",
  "tacio": "Tácio",
  "tania": "Tânia", "tercio": "Tércio",
  "tulio": "Túlio",
  "vinicius": "Vinícius",
  "vitor": "Vítor",
  "zelia": "Zélia",
  "thais": "Thaís",
  "anastacio": "Anastácio", "bonifacio": "Bonifácio",
  "estacio": "Estácio", "pancracio": "Pancrácio",
  "magalhaes": "Magalhães", "guimaraes": "Guimarães",
  "jimenez": "Jiménez",
  "paixao": "Paixão", "assuncao": "Assunção",
  "encarnacao": "Encarnação", "anunciacao": "Anunciação",
  "purificacao": "Purificação",

  "brandao": "Brandão", "galvao": "Galvão", "frazao": "Frazão",
  "falcao": "Falcão", "aragao": "Aragão", "gusmao": "Gusmão",
  "leao": "Leão", "mourao": "Mourão", "estevao": "Estevão",
  "jordao": "Jordão", "damiao": "Damião", "salomao": "Salomão",
  "abraao": "Abraão", "napoleao": "Napoleão", "romao": "Romão",
  "leitao": "Leitão", "pavao": "Pavão", "valadao": "Valadão",
  "beltrao": "Beltrão", "adao": "Adão", "durao": "Durão",
  "girao": "Girão", "antao": "Antão", "irmao": "Irmão",
  "fontao": "Fontão", "bulcao": "Bulcão", "abrahao": "Abraão",

  "franca": "França", "mendonca": "Mendonça", "fogaca": "Fogaça",
  "proenca": "Proença", "braganca": "Bragança", "esperanca": "Esperança",
  "balanco": "Balanço", "goncalo": "Gonçalo", "assumpcao": "Assumpção",
  "bondanca": "Bondança",

  "simoes": "Simões", "duraes": "Durães", "manhaes": "Manhães",
  "bulhoes": "Bulhões", "froes": "Fróes",

  "leticia": "Letícia", "livia": "Lívia", "nathalia": "Nathália",
  "jessica": "Jéssica", "gessica": "Géssica", "jhessica": "Jhéssica",
  "fabricio": "Fabrício", "fabricia": "Fabrícia",
  "cassia": "Cássia", "kassia": "Kássia",
  "venancio": "Venâncio", "amancio": "Amâncio",
  "angelica": "Angélica", "veronica": "Verônica",
  "katia": "Kátia", "lavinia": "Lavínia",
  "marilia": "Marília", "junio": "Júnio",
  "romulo": "Rômulo", "lais": "Laís",
  "sa": "Sá", "gois": "Goís", "avila": "Ávila",
  "silverio": "Silvério", "cesario": "Cesário", "cezario": "Cezário",
  "honorio": "Honório", "gregorio": "Gregório",
  "tenorio": "Tenório", "apolinario": "Apolinário",
  "emilio": "Emílio", "basilio": "Basílio",
  "demetrio": "Demétrio", "marcilio": "Marcílio",
  "patrocinio": "Patrocínio",
  "simplicio": "Simplício",
  "tiberio": "Tibério", "alicia": "Alícia", "thalia": "Thália",
  "andreia": "Andréia", "adesio": "Adésio",
  "cecilio": "Cecílio", "eleuterio": "Eleutério",

  "vitoria": "Vitória", "victoria": "Victória", "vytoria": "Vytória",
  "lourenco": "Lourenço", "italo": "Ítalo",
  "raissa": "Raíssa", "janaina": "Janaína",
  "heloisa": "Heloísa", "eloisa": "Eloísa",
  "taina": "Taína", "tais": "Taís", "laisa": "Laísa",
  "elisangela": "Elisângela", "rosangela": "Rosângela",
  "joice": "Joíce",
  "custodio": "Custódio", "cicero": "Cícero", "cicera": "Cícera",
  "kaue": "Kauê", "caue": "Cauê",
  "octavio": "Octávio", "othavio": "Othávio",
  "americo": "Américo", "damasio": "Damásio", "savio": "Sávio",
  "fabiola": "Fabíola", "agata": "Ágata",
  "ambrosio": "Ambrósio", "egidio": "Egídio",
  "picanco": "Picanço", "cancado": "Cançado",
  "josue": "Josué", "tome": "Tomé",
  "atila": "Átila", "brigida": "Brígida",
  "candida": "Cândida", "emidio": "Emídio",
  "lidia": "Lídia",
  "fabia": "Fábia", "junia": "Júnia",
  "olivia": "Olívia", "olivio": "Olívio",
  "vania": "Vânia", "virginia": "Virgínia",
  "eugenia": "Eugênia", "efigenia": "Efigênia",
  "gardenia": "Gardênia",
  "glaucia": "Gláucia", "glaucio": "Gláucio",
  "lucelia": "Lucélia", "marlucia": "Marlúcia",
  "allicia": "Allícia", "catia": "Cátia",
  "clelia": "Clélia", "adelia": "Adélia",

  "florencio": "Florêncio", "hilario": "Hilário",
  "nazario": "Nazário", "olegario": "Olegário",
  "porfirio": "Porfírio", "romario": "Romário",
  "vinicio": "Vinício", "venicio": "Venício",
  "victorio": "Victório", "vitorio": "Vitório",
  "benicio": "Benício", "inocencio": "Inocêncio",
  "prudencio": "Prudêncio",
  "abilio": "Abílio", "virgilio": "Virgílio",
  "liborio": "Libório", "osorio": "Osório", "ozorio": "Ozório",
  "cornelio": "Cornélio", "janio": "Jânio",
  "juvencio": "Juvêncio", "leoncio": "Leôncio",
  "poncio": "Pôncio", "valencio": "Valêncio",
  "stenio": "Stênio", "pacifico": "Pacífico",
  "admario": "Admário", "aparicio": "Aparício",
  "braulio": "Bráulio", "epifanio": "Epifânio",
  "delminio": "Delmínio", "denio": "Dênio",
  "amelio": "Amélio", "capitanio": "Capitânio",
  "kassio": "Kássio", "rozario": "Rozário",
  "gloria": "Glória", "goes": "Góes",

  "quintao": "Quintão", "serrao": "Serrão", "varjao": "Varjão",
  "abrao": "Abrão", "brazao": "Brazão",
  "tameirao": "Tameirão", "tamiao": "Tamião", "tristao": "Tristão",
  "gastao": "Gastão", "juliao": "Julião", "lobao": "Lobão",
  "militao": "Militão", "pantaleao": "Pantaleão",
  "gaviao": "Gavião", "maranhao": "Maranhão",
  "mergulhao": "Mergulhão", "sabastiao": "Sabastião",
  "batistao": "Batistão", "calvao": "Calvão",
  "esperidiao": "Esperidião",
  "apresentacao": "Apresentação", "consolacao": "Consolação",
  "aarao": "Aarão",

  "alcantara": "Alcântara", "camara": "Câmara",
  "icaro": "Ícaro", "ikaro": "Íkaro",
  "hitalo": "Hítalo",
  "tarcisio": "Tarcísio", "anisio": "Anísio",
  "elizangela": "Elizângela",
  "teofilo": "Teófilo", "tiburcio": "Tibúrcio",
  "espindola": "Espíndola", "davila": "Dávila",
  "brigido": "Brígido",
  "samia": "Sâmia",
  "sabara": "Sabará",
  "maisa": "Maísa", "geisa": "Geísa",
  "maira": "Maíra", "daira": "Daíra",
  "kesia": "Késia", "taila": "Taíla",
  "melonio": "Melônio",
  "rubia": "Rúbia",
  "ligia": "Lígia",
  "euzebio": "Euzébio",
  "lucrecia": "Lucrécia", "mercia": "Mércia",
  "isidio": "Isídio", "izidio": "Izídio",
  "gelio": "Gélio",
  "adria": "Ádria", "eularia": "Eulária",
  "aprigio": "Aprígio",
  "hypolito": "Hypólito",
  "tullio": "Túllio",
  "correa": "Corrêa", "andrea": "Andréa", "dandrea": "D'Andréa",
  "dorea": "Doréa",

  "vinicios": "Vinícios", "winicios": "Winícios", "winicius": "Winícius",
  "pecanha": "Peçanha", "facanha": "Façanha",
  "diogenes": "Diógenes", "aristoteles": "Aristóteles", "aquiles": "Aquíles",
  "nicacio": "Nicácio", "nubia": "Núbia",
  "regis": "Régis", "clovis": "Clóvis",
  "iris": "Íris", "isis": "Ísis",
  "belem": "Belém",
  "fidelis": "Fidélis",
  "jessyca": "Jéssyca",
  "alcebiades": "Alcebíades", "melquiades": "Melquíades",
  "aristides": "Arístides",
  "sansao": "Sansão", "serapiao": "Serapião",

  "kaua": "Kauã", "caua": "Cauã",
  "padua": "Pádua", "gouvea": "Gouvêa", "uchoa": "Uchôa",
  "cinthia": "Cínthia", "kezia": "Kézia",

  "colaco": "Colaço", "collaco": "Collaço", "ciriaco": "Ciríaco",
  "charao": "Charão", "gurjao": "Gurjão", "requiao": "Requião",
  "rondao": "Rondão", "pilao": "Pilão", "perdao": "Perdão",
  "riachao": "Riachão", "sipiao": "Sipião", "espiridao": "Espiridão",
  "garcao": "Garção", "ingrao": "Ingrão", "lugao": "Lugão",
  "reymao": "Reymão", "parriao": "Parrião", "payao": "Payão",
  "gavaldao": "Gavaldão", "garzao": "Garzão", "carrao": "Carrão",
  "marangao": "Marangão", "bertao": "Bertão", "dinao": "Dinão",
  "loucao": "Loucão", "melao": "Melão", "salmeirao": "Salmeirão",
  "aranao": "Aranão", "contao": "Contão", "creao": "Creão",
  "chelegao": "Chelegão", "gussao": "Gussão", "bezzao": "Bezzão",
  "jacao": "Jacão", "marciao": "Marcião", "biao": "Bião",

  "pamela": "Pâmela", "pamella": "Pâmella",
  "nobrega": "Nóbrega", "nazare": "Nazaré",
  "valquiria": "Valquíria", "sodre": "Sodré",
  "danubia": "Danúbia", "tabata": "Tábata",
  "talia": "Tália", "verissimo": "Veríssimo",
  "ataide": "Ataíde", "marcal": "Marçal",
  "noemia": "Noêmia", "quiteria": "Quitéria",
  "simiao": "Simião", "vilaca": "Vilaça",
  "ferrao": "Ferrão", "reboucas": "Rebouças",
  "caceres": "Cáceres", "crisostomo": "Crisóstomo",
  "dionisio": "Dionísio", "dionizio": "Dionízio",
  "hercules": "Hércules", "herica": "Hérica",
  "erico": "Érico", "kenia": "Kênia",
  "gracas": "Graças", "merces": "Mercês",
  "quezia": "Quézia", "betania": "Betânia",
  "tassia": "Tássia", "amalia": "Amália",
  "rene": "Renê", "anisia": "Anísia",
  "lucineia": "Lucinéia", "ivania": "Ivânia",
  "estefania": "Estefânia", "clecio": "Clécio",
  "nivia": "Nívia", "laise": "Laíse",
  "taise": "Taíse", "laize": "Laíze",
  "heloiza": "Heloíza", "herika": "Hérika",
  "jessika": "Jéssika", "deborah": "Déborah",
  "thamara": "Thâmara", "elida": "Élida",
  "venycius": "Venícius", "vinycius": "Vinícius",

  "thaina": "Thaína", "tainara": "Taínara", "thainara": "Thaínara",
  "vanderleia": "Vanderléia", "vanderlei": "Vanderléi",
  "thaisa": "Thaísa", "thaise": "Thaíse",
  "alexia": "Aléxia", "ataides": "Ataídes",
  "alvares": "Álvares", "miqueias": "Miquéias",
  "claudineia": "Claudinéia", "sthefany": "Sthéfany",

  "nelia": "Nélia", "joselia": "Josélia",
  "jucelia": "Jucélia", "noelia": "Noélia",
  "edileia": "Ediléia", "lucileia": "Luciléia",
  "valdineia": "Valdinéia", "edineia": "Edinéia",
  "rosicleia": "Rosicléia", "janecleia": "Janecléia",
  "janicleia": "Janicléia", "josileia": "Josiléia",
  "cleia": "Cléia", "dulcineia": "Dulcinéia",
  "alecia": "Alécia", "cleucia": "Cleúcia",
  "pericles": "Péricles", "leonidas": "Leônidas",
  "demostenes": "Demóstenes", "lucrecio": "Lucrécio",
  "valenca": "Valença", "herminia": "Hermínia",
  "walquiria": "Walquíria", "inacia": "Inácia",
  "anastacia": "Anastácia",

  "stefany": "Stéfany", "stefani": "Stéfani",
  "stefane": "Stéfane", "stefanie": "Stéfanie",
  "stefanny": "Stéfanny", "stefeny": "Stéfeny",
  "sthefani": "Sthéfani", "sthefane": "Sthéfane",
  "sthefanny": "Sthéfanny", "stheffany": "Sthéffany",
  "estefani": "Estéfani", "estefane": "Estéfane",
  "estefany": "Estéfany", "estefanie": "Estéfanie",
  "estefanny": "Estéfanny", "steffani": "Stéffani",
  "taissa": "Taíssa", "thaissa": "Thaíssa",
  "taisa": "Taísa", "taiza": "Taíza", "thaiza": "Thaíza",
  "marileia": "Mariléia", "ivaneia": "Ivanéia",
  "jocelia": "Jocélia", "leia": "Léia",
  "doroteia": "Dorotéia", "genesia": "Genésia",
  "idalia": "Idália", "constancia": "Constância",
  "valdenia": "Valdênia", "atanasio": "Atanásio",
  "eufrasio": "Eufrásio", "acacio": "Acácio",
  "dacio": "Dácio", "eustaquio": "Eustáquio",
  "leocadio": "Leocádio", "penelope": "Penélope",
  "jesuino": "Jesuíno", "jessyka": "Jéssyka",

  "timoteo": "Timóteo", "sidonio": "Sidônio",
  "petronio": "Petrônio", "grigorio": "Grigório",
  "onorio": "Onório", "teodorio": "Teodório",
  "hermogenes": "Hermógenes",
  "viktoria": "Viktória", "vittoria": "Vittória",
  "midia": "Mídia", "espirito": "Espírito",
  "salome": "Salomé", "gedeao": "Gedeão",
  "cantao": "Cantão", "islabao": "Islabão",
  "primao": "Primão", "santarem": "Santarém",

  "negrao": "Negrão", "arao": "Arão",
  "montalvao": "Montalvão", "barao": "Barão",
  "perdigao": "Perdigão", "visitacao": "Visitação",
  "elesbao": "Elesbão", "gaiao": "Gaião",
  "melgaco": "Melgaço", "climaco": "Clímaco",
  "camurca": "Camurça", "calaca": "Calaça",
  "florenco": "Florenço", "jaco": "Jacó",
  "moco": "Moço", "gessyca": "Géssyca", "jesica": "Jésica",
  "aldineia": "Aldinéia", "rosineia": "Rosinéia",
  "sidneia": "Sidnéia", "edneia": "Ednéia",
  "arimateia": "Arimatéia",
  "lethicia": "Lethícia", "licia": "Lícia",
  "clicia": "Clícia", "laudiceia": "Laudicéia",
  "katiucia": "Katiúcia", "laricia": "Larícia",
  "adricia": "Adrícia", "clissia": "Clíssia",
  "stefania": "Stéfania", "steffane": "Stéffane",
  "esteffany": "Estéffany", "stefanne": "Stéfanne",
  "stefanni": "Stéfanni", "stefhany": "Stéfhany",
  "amelia": "Amélia", "lilia": "Lília",
  "waleria": "Waléria", "rogeria": "Rogéria",
  "eulalia": "Eulália", "mauricelia": "Mauricélia",
  "anatalia": "Anatália", "magnolia": "Magnólia",
  "maricelia": "Maricélia", "adilia": "Adília",
  "witoria": "Witória",
  "roberio": "Robério", "sudario": "Sudário",
  "desiderio": "Desidério", "belizario": "Belizário",
  "eliziario": "Eliziário", "glicerio": "Glicério",
  "cantuario": "Cantuário", "deziderio": "Dezidério",
  "belisario": "Belisário", "isidorio": "Isidório",
  "izidorio": "Izidório",
  "teodosio": "Teodósio", "alipio": "Alípio",
  "remigio": "Remígio", "cantidio": "Cantídio",
  "gervasio": "Gervásio", "anizio": "Anízio",
  "eufrazio": "Eufrázio", "damazio": "Damázio",
  "atanazio": "Atanázio", "abadio": "Abádio",
  "danuzia": "Danúzia", "quesia": "Quésia",
  "dionisia": "Dionísia", "kelvia": "Kélvia",
  "elvia": "Élvia", "tassio": "Tássio",
  "otacilio": "Otacílio", "palacio": "Palácio",
  "melquiades": "Melquíades", "ordonio": "Ordônio",
  "porciuncula": "Porciúncula", "ursula": "Úrsula",
  "fabiula": "Fabíula", "espindula": "Espíndula",
  "socrates": "Sócrates", "arquimedes": "Arquímedes",

  "catao": "Catão", "camarao": "Camarão",
  "moncao": "Monção", "beirao": "Beirão",
  "roldao": "Roldão", "sayao": "Sayão",
  "exaltacao": "Exaltação", "gideao": "Gideão",
  "ressurreicao": "Ressurreição", "baiao": "Baião",
  "semeao": "Semeão", "simeao": "Simeão",
  "botao": "Botão", "remiao": "Remião",
  "rumao": "Rumão", "ramao": "Ramão",
  "sadao": "Sadão", "sancao": "Sanção",
  "atarao": "Atarão", "dalbao": "Dalbão",
  "lourenca": "Lourença", "saragoca": "Saragoça",
  "florencia": "Florência", "paciencia": "Paciência",
  "esperanca": "Esperança",
  "steffany": "Stéffany", "sthefanne": "Sthéfanne",
  "esteffani": "Estéffani",
  "edicleia": "Edicléia", "valdileia": "Valdiléia",
  "jucileia": "Juciléia", "gisleia": "Gisléia",
  "jocicleia": "Jocicléia", "adneia": "Adnéia",
  "laodiceia": "Laodicéia", "mauriceia": "Mauricéia",
  "nilceia": "Nilcéia", "rosecleia": "Rosecléia",
  "rutineia": "Rutinéia",
  "dalia": "Dália", "dilcelia": "Dilcélia",
  "auricelia": "Auricélia", "waldicelia": "Waldicélia",
  "gizelia": "Gizélia", "iracelia": "Iracélia",
  "giselia": "Gisélia", "gilcelia": "Gilcélia",
  "joelia": "Joélia", "juscelia": "Juscélia",
  "juzelia": "Juzélia", "ercilia": "Ercília",
  "marcelia": "Marcélia",
  "silvania": "Silvânia", "gilvania": "Gilvânia",
  "jordania": "Jordânia", "lucivania": "Lucivânia",
  "erivania": "Erivânia", "rosania": "Rosânia",
  "rosivania": "Rosivânia", "elivania": "Elivânia",
  "vanderlania": "Vanderlânia", "islania": "Islânia",
  "quenia": "Quênia", "hortencia": "Hortência",
  "hortencio": "Hortêncio", "merencio": "Merêncio",
  "gaudencio": "Gaudêncio", "constancio": "Constâncio",
  "fidencio": "Fidêncio", "jovencio": "Jovêncio",
  "cancio": "Câncio",
  "kercia": "Kércia", "tarcio": "Tárcio",
  "tercia": "Tércia", "laercio": "Laércio",
  "walkiria": "Walkíria", "valkiria": "Valkíria",
  "gicelia": "Gicélia", "hercilia": "Hercília",
  "lucelio": "Lucélio", "mamedio": "Mamédio",
  "alecio": "Alécio", "kissia": "Kíssia",
  "kecia": "Kécia", "klivia": "Klívia",
  "kivia": "Kívia", "helia": "Hélia",
  "glicia": "Glícia", "analia": "Anália",
  "ambrozio": "Ambrózio", "luzio": "Lúzio",
  "leonidio": "Leonídio", "gilmaria": "Gilmária",
  "istefania": "Istéfania",
  "vivia": "Vívia", "edivania": "Edivânia",
  "edvania": "Edvânia", "rocio": "Rócio",
  "bethania": "Bethânia", "lanuzia": "Lanúzia",
  "katiuscia": "Katiúscia", "timotio": "Timótio",

  "kessia": "Késsia", "miria": "Míria",
  "abadia": "Abádia", "virginio": "Virgínio",
  "plinio": "Plínio", "apolonio": "Apolônio",
  "evania": "Evânia", "herminio": "Hermínio",
  "vergilio": "Vergílio", "arsenio": "Arsênio",
  "enio": "Ênio", "maurilio": "Maurílio",
  "felicia": "Felícia", "aloisio": "Aloísio",
  "fulgencio": "Fulgêncio", "crescencio": "Crescêncio",
  "clecia": "Clécia", "rizia": "Rízia",
  "iria": "Íria", "mauricelio": "Mauricélio",
  "elio": "Élio", "cantuaria": "Cantuária",
  "galucio": "Galúcio", "otavia": "Otávia",
  "elvio": "Élvio", "demezio": "Demézio",
  "protazio": "Protázio", "bazilio": "Bazílio",
  "romaria": "Romária", "silvanio": "Silvânio",
  "sinesio": "Sinésio", "sintia": "Síntia",
  "elizia": "Elízia", "tacia": "Tácia",
  "elisia": "Elísia", "clesia": "Clésia",
  "rivia": "Rívia", "suenia": "Suênia",
  "tarcia": "Tárcia", "alicio": "Alício",
  "temotio": "Temótio", "teotonio": "Teotônio",
  "terencio": "Terêncio", "thassia": "Thássia",
  "tricia": "Trícia", "valclecia": "Valclécia",
  "valencia": "Valência", "aldenia": "Aldênia",
  "valleria": "Valléria", "alania": "Alânia",
  "vanderlucio": "Vanderlúcio", "aecio": "Aécio",
  "vanusia": "Vanúsia", "vanuzia": "Vanúzia",
  "venancia": "Venância", "victtoria": "Victtória",
  "vilmaria": "Vilmária", "ademario": "Ademário",
  "eusebio": "Eusébio", "eutropio": "Eutrópio",
  "ezio": "Ézio", "escorcio": "Escórcio",
  "erlandia": "Erlândia", "erisvania": "Erisvânia",
  "fabrizia": "Fabrízia", "fabrizzio": "Fabrízzio",
  "erio": "Ério", "francelio": "Francélio",
  "francivania": "Francivânia", "fulvia": "Fúlvia",
  "galdencio": "Galdêncio", "ganancio": "Ganâncio",
  "engracio": "Engrácio", "genario": "Genário",
  "geovania": "Geovânia", "gilcelio": "Gilcélio",
  "gildasio": "Gildásio", "erquicia": "Erquícia",
  "acacia": "Acácia", "aluizio": "Aluízio",
  "amarilio": "Amarílio", "apolinaria": "Apolinária",
  "artemio": "Artêmio", "badia": "Bádia",
  "cacia": "Cácia", "calacio": "Calácio",
  "calvario": "Calvário", "canario": "Canário",
  "candelaria": "Candelária", "cantoario": "Cantoário",
  "catiucia": "Catiúcia", "cidia": "Cídia",
  "claudenia": "Claudênia", "clebia": "Clébia",
  "clenio": "Clênio", "clesio": "Clésio",
  "clessia": "Cléssia", "darcio": "Dárcio",
  "demesio": "Demésio", "deoclecio": "Deoclécio",
  "domicio": "Domício", "edilania": "Edilânia",
  "edisio": "Edísio", "eladia": "Eládia",
  "elania": "Elânia", "elcia": "Élcia",
  "eleoterio": "Eleotério", "elia": "Élia",
  "elidio": "Elídio", "eliezio": "Eliézio",
  "gilsonia": "Gilsônia", "gilvanio": "Gilvânio",
  "gracia": "Grácia", "helcio": "Hélcio",
  "helvecio": "Helvécio", "heraclio": "Heráclio",
  "herenio": "Herênio", "imidio": "Imídio",
  "januaria": "Januária", "josimario": "Josimário",
  "josivania": "Josivânia", "jovania": "Jovânia",
  "kacio": "Kácio", "kessio": "Késsio",
  "kevia": "Kévia", "klesia": "Klésia",
  "leidivania": "Leidivânia", "leocadia": "Leocádia",
  "licerio": "Licério", "limirio": "Limírio",
  "liria": "Líria", "lirio": "Lírio",
  "lizia": "Lízia", "loterio": "Lotério",
  "lucilio": "Lucílio", "ludgerio": "Ludgério",
  "ludia": "Lúdia", "lusia": "Lúsia",
  "maritania": "Maritânia", "montania": "Montânia",
  "nalerio": "Nalério", "natania": "Natânia",
  "nisia": "Nísia", "nuria": "Núria",
  "odocia": "Odócia", "olimpia": "Olímpia",
  "oliverio": "Olivério", "ovidio": "Ovídio",
  "pastorio": "Pastório", "perminio": "Permínio",
  "petrucio": "Petrúcio", "possidonio": "Possidônio",
  "profirio": "Profírio", "quintania": "Quintânia",
  "roberia": "Robéria", "roberlandia": "Roberlândia",
  "roselandia": "Roselândia", "sanzio": "Sânzio",
  "sperandio": "Sperândio", "stephania": "Stéphania",
  "sthephania": "Sthéphania", "tailania": "Tailânia",
  "vyctoria": "Vyctória", "wenia": "Wênia",
  "zilmaria": "Zilmária", "cinaria": "Cinária",
  "tadao": "Tadão", "euripedes": "Eurípedes",

  "abilia": "Abília", "adalicio": "Adalício",
  "adelucia": "Adelúcia", "adenilia": "Adenília",
  "adilio": "Adílio", "adrielio": "Adriélio",
  "advania": "Advânia", "afranio": "Afrânio",
  "agricia": "Agrícia", "akesia": "Akésia",
  "alberio": "Albério", "alcindelia": "Alcindélia",
  "aldenio": "Aldênio", "alderonio": "Alderônio",
  "alessio": "Aléssio", "aluisio": "Aluísio",
  "amancia": "Amância", "amaurilio": "Amaurílio",
  "amazilia": "Amazília", "anailia": "Anaília",
  "analicia": "Analícia", "andrenia": "Andrênia",
  "anibal": "Aníbal", "anicio": "Anício",
  "anilia": "Anília", "anselia": "Ansélia",
  "anterio": "Antério", "anthonio": "Anthônio",
  "antonisia": "Antonísia", "apolimario": "Apolimário",
  "apolonia": "Apolônia", "appolinario": "Appolinário",
  "aracelia": "Aracélia", "arathusia": "Arathúsia",
  "arcelucia": "Arcelúcia", "arcenio": "Arcênio",
  "aricelia": "Aricélia", "aricia": "Arícia",
  "arlenio": "Arlênio", "artenio": "Artênio",
  "artilia": "Artília", "ascencio": "Ascêncio",
  "assencio": "Assêncio", "audario": "Audário",
  "auricelio": "Auricélio", "aurilia": "Aurília",
  "balduino": "Balduíno", "belisiario": "Belisiário",
  "benonia": "Benônia", "bertalucia": "Bertalúcia",
  "beybyvania": "Beybyvânia", "blicia": "Blícia",
  "boecio": "Boécio", "bolanio": "Bolânio",
  "bonizario": "Bonizário", "bricidio": "Bricídio",
  "brunelio": "Brunélio", "bulio": "Búlio",
  "caldaria": "Caldária", "calizario": "Calizário",
  "callegario": "Callegário", "candelario": "Candelário",
  "canterucio": "Canterúcio", "cardenia": "Cardênia",
  "caria": "Cária", "carisio": "Carísio",
  "carmelia": "Carmélia", "carmelio": "Carmélio",
  "castimario": "Castimário", "cattanio": "Cattânio",
  "cedonia": "Cedônia", "celedonio": "Celedônio",
  "celenia": "Celênia", "celismenia": "Celismênia",
  "cesaria": "Cesária", "cheria": "Chéria",
  "cidio": "Cídio", "cizilvania": "Cizilvânia",
  "claudielia": "Claudiélia", "cleanio": "Cleânio",
  "clemaria": "Clemária", "clerio": "Clério",
  "clezia": "Clézia", "concecio": "Concécio",
  "concilio": "Concílio", "crecencio": "Crecêncio",
  "credidio": "Credídio", "crislania": "Crislânia",
  "daislania": "Daislânia", "dalpicio": "Dalpício",
  "dandaria": "Dandária", "danusia": "Danúsia",
  "darilia": "Darília", "delania": "Delânia",
  "delia": "Délia", "delvania": "Delvânia",
  "deniaria": "Deniária", "denilia": "Denília",
  "denisia": "Denísia", "deusdario": "Deusdário",
  "deusdelia": "Deusdélia", "devenezio": "Devenézio",
  "dhulia": "Dhúlia", "dilvania": "Dilvânia",
  "diovania": "Diovânia", "divania": "Divânia",
  "djivania": "Djivânia", "docilio": "Docílio",
  "dorzanio": "Dorzânio", "duilio": "Duílio",
  "eclisia": "Eclísia", "edclecia": "Edclécia",
  "edelvania": "Edelvânia", "ediclecio": "Ediclécio",
  "edilecia": "Edilécia", "edilucia": "Edilúcia",
  "edilvania": "Edilvânia", "edmaria": "Edmária",
  "edmario": "Edmário", "edquesia": "Edquésia",
  "egidia": "Egídia", "ekenia": "Ekênia",
  "elaisa": "Elaísa", "elcimaria": "Elcimária",
  "eleutherio": "Eleuthério", "elicia": "Elícia",
  "eliesio": "Eliésio", "elioterio": "Eliothério",
  "elisiario": "Elisiário", "elisio": "Elísio",
  "elisvania": "Elisvânia", "elitania": "Elitânia",
  "elizania": "Elizânia", "eliziania": "Eliziânia",
  "elpidio": "Elpídio", "elvania": "Elvânia",
  "emerencio": "Emerêncio", "enia": "Ênia",
  "enidia": "Enídia", "epifania": "Epifânia",
  "erdonio": "Erdônio", "ericlecio": "Ericlécio",
  "erislania": "Erislânia", "erlania": "Erlânia",
  "erlanio": "Erlânio", "eslania": "Eslânia",
  "esmeria": "Esméria", "esterfania": "Esterfânia",
  "etienia": "Etiênia", "evanio": "Evânio",
  "everonia": "Everônia", "ezidio": "Ezídio",
  "facanario": "Facanário", "famaria": "Famária",
  "farnesio": "Farnésio", "fedencio": "Fedêncio",
  "feria": "Féria", "flerio": "Flério",
  "florio": "Flório", "fornazario": "Fornazário",
  "francilicio": "Francilício", "francimaria": "Francimária",
  "franciaria": "Franciária", "francuelio": "Francuélio",
  "frigerio": "Frigério", "galdemia": "Galdêmia",
  "galgania": "Galgânia", "genario": "Genário",
  "genezio": "Genézio", "genicelia": "Genicélia",
  "genuino": "Genuíno", "geovanio": "Geovânio",
  "gercimaria": "Gercimária", "gerdenia": "Gerdênia",
  "gerlania": "Gerlânia", "germanio": "Germânio",
  "gersivania": "Gersivânia", "gersonia": "Gersônia",
  "gesevania": "Gesevânia", "giclesia": "Giclésia",
  "gilblenia": "Gilblênia", "gilcivania": "Gilcivânia",
  "gilclezia": "Gilclézia", "gildenio": "Gildênio",
  "gilderlania": "Gilderlânia", "gildonio": "Gildônio",
  "gilia": "Gília", "gilio": "Gílio",
  "gilmario": "Gilmário", "girlania": "Girlânia",
  "gisvania": "Gisvânia", "giulio": "Giúlio",
  "gleicia": "Gleícia", "gleicivania": "Gleicivânia",
  "glecia": "Glécia", "glezia": "Glézia",
  "guivanio": "Guivânio", "hanania": "Hanânia",
  "hancio": "Hâncio", "hania": "Hânia",
  "harlenio": "Harlênio", "helanio": "Helânio",
  "helder": "Hélder", "henio": "Hênio",
  "herbenia": "Herbênia", "hermicio": "Hermício",
  "hermogenio": "Hermogênio", "honostorio": "Honostório",
  "hylario": "Hylário", "icenia": "Icênia",
  "idalencio": "Idalêncio", "idamaria": "Idamária",
  "idelucia": "Idelúcia", "iglesia": "Iglésia",
  "ilario": "Ilário", "ilidio": "Ilídio",
  "imbronisio": "Imbronísio", "irenio": "Irênio",
  "irisvania": "Irisvânia", "ismenia": "Ismênia",
  "itania": "Itânia", "iulio": "Iúlio",
  "ivanio": "Ivânio", "ivandaria": "Ivandária",
  "ivoneria": "Ivonéria", "izania": "Izânia",
  "jacimario": "Jacimário", "jacivania": "Jacivânia",
  "jailucia": "Jailúcia", "jaira": "Jaíra",
  "jaisa": "Jaísa", "janaira": "Janaíra",
  "jandaira": "Jandaíra", "janciaria": "Janciária",
  "janicelia": "Janicélia", "jardenia": "Jardênia",
  "jassaria": "Jassária", "jaucivania": "Jaucivânia",
  "jenuaria": "Januária", "jenuino": "Jenuíno",
  "jessenia": "Jessênia", "jessielia": "Jessiélia",
  "jizania": "Jizânia", "joania": "Joânia",
  "joanilia": "Joanília", "jociaria": "Jociária",
  "joicelia": "Joicélia", "jomario": "Jomário",
  "joselio": "Josélio", "josevania": "Josevânia",
  "jozelia": "Jozélia", "jozimaria": "Jozimária",
  "jucielia": "Juciélia", "jucinelia": "Jucinélia",
  "jucivania": "Jucivânia", "kaira": "Kaíra",
  "kaila": "Kaíla", "karlania": "Karlânia",
  "karilia": "Karília", "karusia": "Karúsia",
  "katricia": "Katrícia", "kenio": "Kênio",
  "klesia": "Klésia", "klezia": "Klézia",
  "klicia": "Klícia", "klenio": "Klênio",
  "laira": "Laíra", "laissa": "Laíssa",
  "laiza": "Laíza", "lalenia": "Lalênia",
  "lastenia": "Lastênia", "latavania": "Latavânia",
  "lauricio": "Laurício", "lauterio": "Lautério",
  "lelio": "Lélio", "leomaria": "Leomária",
  "leovania": "Leovânia", "leridia": "Lerídia",
  "letticia": "Lettícia", "laeticia": "Laetícia",
  "libanio": "Libânio", "libania": "Libânia",
  "liberia": "Libéria", "licio": "Lício",
  "liduino": "Liduíno", "livanio": "Livânio",
  "lidivania": "Lidivânia", "ligorio": "Ligório",
  "lohania": "Lohânia", "lorrania": "Lorrânia",
  "louize": "Louíze", "lourencia": "Lourência",
  "lourencio": "Lourêncio", "lucilia": "Lucília",
  "lucilania": "Lucilânia", "lucimaria": "Lucimária",
  "lucicrecia": "Lucicrécia", "ludgerio": "Ludgério",
  "ludugerio": "Ludugério", "luise": "Luíse",
  "luiza": "Luíza", "luize": "Luíze",
  "luizza": "Luízza", "luismario": "Luismário",
  "luzitania": "Luzitânia", "luzivania": "Luzivânia",
  "macedonia": "Macedônia", "macinesia": "Macinésia",
  "maezia": "Maézia", "magnania": "Magnânia",
  "maila": "Maíla", "maiza": "Maíza",
  "malicio": "Malício", "mancia": "Mância",
  "mansilia": "Mansília", "maraisa": "Maraísa",
  "maraiza": "Maraíza", "marcantonio": "Marcantônio",
  "marcilia": "Marcília", "marcionilia": "Marcionília",
  "marcionilio": "Marcionílio", "marilania": "Marilânia",
  "marilucia": "Marilúcia", "marivania": "Marivânia",
  "marizelia": "Marizélia", "maronio": "Marônio",
  "marsilio": "Marsílio", "martilio": "Martílio",
  "marylucia": "Marylúcia", "mazario": "Mazário",
  "melania": "Melânia", "melicia": "Melícia",
  "mesia": "Mésia", "mestancio": "Mestâncio",
  "mikecia": "Mikécia", "miquelia": "Miquélia",
  "mirlania": "Mirlânia", "moacilio": "Moacílio",
  "molinario": "Molinário", "monaria": "Monária",
  "monia": "Mônia", "mucio": "Múcio",
  "mylwania": "Mylwânia", "nacilio": "Nacílio",
  "naila": "Naíla", "naira": "Naíra",
  "narcezio": "Narcézio", "naria": "Nária",
  "natalicio": "Natalício", "nemesia": "Nemésia",
  "neovania": "Neovânia", "nercilia": "Nercília",
  "neria": "Néria", "nezia": "Nézia",
  "neylivania": "Neylivânia", "nicelia": "Nicélia",
  "nicezio": "Nicézio", "nicia": "Nícia",
  "nidia": "Nídia", "nilania": "Nilânia",
  "nilcelia": "Nilcélia", "nilmario": "Nilmário",
  "nilvania": "Nilvânia", "niquesia": "Niquésia",
  "noberlania": "Noberlânia", "noelio": "Noélio",
  "normelia": "Normélia", "nuriacelia": "Nuriacélia",
  "ocelio": "Océlio", "oclecio": "Oclécio",
  "odilia": "Odília", "odilio": "Odílio",
  "odoricio": "Odorício", "oleria": "Oléria",
  "olevario": "Olevário", "olezio": "Olézio",
  "olicerio": "Olicério", "onelia": "Onélia",
  "oracilia": "Oracília", "orlania": "Orlânia",
  "ormesia": "Ormésia", "ormicelia": "Ormicélia",
  "oricio": "Orício", "osania": "Osânia",
  "osenelia": "Osenélia", "osmario": "Osmário",
  "pablicia": "Pablícia", "pablicio": "Pablício",
  "palancio": "Palâncio", "palmerio": "Palmério",
  "paltilia": "Paltília", "pamfilio": "Pamfílio",
  "panfilio": "Panfílio", "panisio": "Panísio",
  "pauperio": "Paupério", "pecedonio": "Pecedônio",
  "pegorario": "Pegorário", "percilio": "Percílio",
  "peronio": "Perônio", "petronilia": "Petronília",
  "petronilio": "Petronílio", "piao": "Pião",
  "placidio": "Placídio", "policario": "Policário",
  "polidorio": "Polidório", "polonio": "Polônio",
  "pompilio": "Pompílio", "poncidonio": "Poncidônio",
  "priscilia": "Priscília", "procidonio": "Procidônio",
  "profirio": "Profírio", "protencio": "Protêncio",
  "pruencio": "Pruêncio", "pulcherio": "Pulchério",
  "quecia": "Quécia", "quiterio": "Quitério",
  "raglicia": "Raglícia", "raila": "Raíla",
  "raisa": "Raísa", "raiza": "Raíza",
  "ramilio": "Ramílio", "rejulio": "Rejúlio",
  "rhaira": "Rhaíra", "rhaissa": "Rhaíssa",
  "risia": "Rísia", "rismaria": "Rismária",
  "roblesia": "Roblésia", "romerio": "Romério",
  "rosaria": "Rosária", "roselia": "Rosélia",
  "rosemaria": "Rosemária", "rosicleria": "Rosicléria",
  "rosilio": "Rosílio", "rozimaria": "Rozimária",
  "rozonia": "Rozônia", "rubervania": "Rubervânia",
  "rubevania": "Rubevânia", "rublevania": "Rublevânia",
  "rudenio": "Rudênio", "sanaria": "Sanária",
  "sanario": "Sanário", "sancia": "Sância",
  "sangregorio": "Sangregório", "santamaria": "Santamária",
  "santerio": "Santério", "satilia": "Satília",
  "selia": "Sélia", "selio": "Sélio",
  "selivania": "Selivânia", "senario": "Senário",
  "senio": "Sênio", "sezario": "Sezário",
  "siberia": "Sibéria", "siderio": "Sidério",
  "sidronio": "Sidrônio", "silania": "Silânia",
  "silaria": "Silária", "silesia": "Silésia",
  "silezio": "Silézio", "siliverio": "Silivério",
  "silmaria": "Silmária", "silverlania": "Silverlânia",
  "simaria": "Simária", "simonia": "Simônia",
  "sinaidia": "Sinaídia", "sinesia": "Sinésia",
  "smanio": "Smânio", "steffania": "Stéffania",
  "sthefania": "Sthéfania", "sylvania": "Sylvânia",
  "tamara": "Tâmara", "tanisia": "Tanísia",
  "tarquino": "Tarquíno", "tarsisio": "Tarsísio",
  "tecia": "Técia", "telmario": "Telmário",
  "teonilia": "Teonília", "teotonia": "Teotônia",
  "thaila": "Thaíla", "thalilia": "Thalília",
  "thania": "Thânia", "tharcisio": "Tharcísio",
  "thelio": "Thélio", "theotonio": "Theotônio",
  "thulia": "Thúlia", "thulio": "Thúlio",
  "tonia": "Tônia", "tonilio": "Tonílio",
  "ubelanio": "Ubelânio", "uenio": "Uênio",
  "valcelio": "Valcélio", "valcidio": "Valcídio",
  "valdicelia": "Valdicélia", "valdimaria": "Valdimária",
  "valdinesia": "Valdinésia", "valecio": "Valécio",
  "valnicio": "Valnício", "vanderlucia": "Vanderlúcia",
  "vandricia": "Vandrícia", "vaneria": "Vanéria",
  "vanezia": "Vanézia", "vanucia": "Vanúcia",
  "ventania": "Ventânia", "veralucia": "Veralúcia",
  "verucia": "Verúcia", "vicencio": "Vicêncio",
  "vicktoria": "Vicktória", "victhoria": "Victhória",
  "viricio": "Virício", "wania": "Wânia",
  "welisvania": "Welisvânia", "wellitania": "Wellitânia",
  "whelia": "Whélia", "wilcliania": "Wilcliânia",
  "winario": "Winário", "wittoria": "Wittória",
  "xenia": "Xênia", "ynaira": "Ynaíra",
  "ysmenia": "Ysmênia", "zaira": "Zaíra",
  "zaria": "Zária", "zevanio": "Zevânio",
  "ziderio": "Zidério", "zilio": "Zílio",

  "raira": "Raíra", "daisa": "Daísa",
  "jaissa": "Jaíssa", "maissa": "Maíssa",
  "naisa": "Naísa", "naiza": "Naíza",
  "rhaiza": "Rhaíza", "milaisa": "Milaísa",
  "odaisa": "Odaísa", "odaiza": "Odaíza",
  "eluiza": "Eluíza", "enaluiza": "Enaluíza",
  "analuiza": "Analuíza", "jesuina": "Jesuína",
  "iduino": "Iduíno", "zesuino": "Zesuíno",
};

function removeAccents(str: string): string {
  return str.normalize("NFD").replace(/[\u0300-\u036f]/g, "");
}

export function formatName(rawName: string): string {
  if (!rawName || typeof rawName !== "string") return rawName || "";

  const trimmed = rawName.trim();
  if (!trimmed) return "";

  const words = trimmed.toLowerCase().split(/\s+/);

  const formatted = words.map((word, index) => {
    if (PREPOSITIONS.has(word) && index !== 0) {
      return word;
    }

    const normalized = removeAccents(word);

    if (ACCENT_MAP[normalized]) {
      return ACCENT_MAP[normalized];
    }

    return word.charAt(0).toUpperCase() + word.slice(1);
  });

  return formatted.join(" ");
}
