// Dados cadastrais fornecidos para este domínio, sem validação externa.
export const EDITAL_PENAL_COMPANY = {
  hostname: 'editalpenal.click',
  brand: 'Regnum Entretenimento',
  razaoSocial: 'Konig Producoes LTDA',
  cnpj: '64184597000154',
  cnpjFormatted: '64.184.597/0001-54',
  endereco: 'Quadra Qms 49 Lote 03 Apto 503, SN',
  bairro: 'Setor de Mansoes de Sobradinho',
  cidade: 'Brasília',
  estado: 'DF',
  cep: '73080-120',
  enderecoCompleto: 'Quadra Qms 49 Lote 03 Apto 503, SN · Setor de Mansoes de Sobradinho · Brasília/DF · CEP 73080-120',
  canonicalUrl: 'https://www.editalpenal.click/',
  email: 'sams.olivs@gmail.com',
  telefone: '(61) 98181-6284',
  naturezaJuridica: 'Sociedade Empresária Limitada',
  dataAbertura: '27/12/2025',
  capitalSocial: 'R$ 10.000,00',
  nomeFantasia: 'Regnum Entretenimento',
  porte: 'Empresa de Pequeno Porte',
  opcaoMei: 'Não',
  opcaoSimples: 'Sim',
  dataOpcaoSimples: '29/12/2025',
  tipoEstabelecimento: 'Matriz',
  situacaoCadastral: 'Ativa',
  dataSituacaoCadastral: '27/12/2025',
} as const;
