/**
 * Retorna uma frase aleatória em inglês e português.
 * @returns {{ en: string, pt: string }} Objeto contendo a frase em inglês (en) e português (pt).
 */
export function getFraseAleatoria() {
  const frases = [
    { en: "The sun rises in the east every morning.", pt: "O sol nasce no leste todas as manhãs." },
    { en: "She always drinks coffee before work.", pt: "Ela sempre toma café antes do trabalho." },
    { en: "My dog loves to play in the park.", pt: "Meu cachorro adora brincar no parque." },
    { en: "We are going to the beach tomorrow.", pt: "Nós vamos à praia amanhã." },
    { en: "He reads a book every night.", pt: "Ele lê um livro toda noite." },
    { en: "The children are laughing in the garden.", pt: "As crianças estão rindo no jardim." },
    { en: "I need to buy some milk at the store.", pt: "Eu preciso comprar leite na loja." },
    { en: "This cake tastes delicious.", pt: "Este bolo está delicioso." },
    { en: "They live in a small house near the river.", pt: "Eles moram em uma casa pequena perto do rio." },
    { en: "My sister is learning to play the piano.", pt: "Minha irmã está aprendendo a tocar piano." },
    { en: "The weather is beautiful today.", pt: "O tempo está lindo hoje." },
    { en: "I forgot my keys at home.", pt: "Esqueci minhas chaves em casa." },
    { en: "We had a great time at the party.", pt: "Nós nos divertimos muito na festa." },
    { en: "He speaks three languages fluently.", pt: "Ele fala três idiomas fluentemente." },
    { en: "The train arrives at eight o'clock.", pt: "O trem chega às oito horas." },
    { en: "She bought a new dress for the wedding.", pt: "Ela comprou um vestido novo para o casamento." },
    { en: "My brother works as a doctor.", pt: "Meu irmão trabalha como médico." },
    { en: "The movie was really exciting.", pt: "O filme foi muito emocionante." },
    { en: "I love walking in the rain.", pt: "Eu amo caminhar na chuva." },
    { en: "The cat is sleeping on the sofa.", pt: "O gato está dormindo no sofá." },
    { en: "We need more vegetables in our diet.", pt: "Precisamos de mais vegetais na nossa dieta." },
    { en: "He drives a red car.", pt: "Ele dirige um carro vermelho." },
    { en: "The library closes at nine.", pt: "A biblioteca fecha às nove." },
    { en: "I enjoy listening to classical music.", pt: "Eu gosto de ouvir música clássica." },
    { en: "She writes poems in her free time.", pt: "Ela escreve poemas no tempo livre." },
    { en: "The mountains look amazing at sunset.", pt: "As montanhas ficam incríveis ao pôr do sol." },
    { en: "My parents are coming to visit next week.", pt: "Meus pais virão me visitar na próxima semana." },
    { en: "He lost his wallet on the bus.", pt: "Ele perdeu a carteira no ônibus." },
    { en: "The baby is sleeping peacefully.", pt: "O bebê está dormindo tranquilamente." },
    { en: "We celebrated his birthday yesterday.", pt: "Comemoramos o aniversário dele ontem." },
    { en: "I usually wake up at six in the morning.", pt: "Eu geralmente acordo às seis da manhã." },
    { en: "The coffee shop is always crowded.", pt: "A cafeteria está sempre cheia." },
    { en: "She teaches English at a local school.", pt: "Ela ensina inglês em uma escola local." },
    { en: "The flowers in the garden are blooming.", pt: "As flores no jardim estão florescendo." },
    { en: "I want to travel around the world.", pt: "Quero viajar pelo mundo." },
    { en: "He plays football every Saturday.", pt: "Ele joga futebol todo sábado." },
    { en: "The soup is too hot to eat.", pt: "A sopa está quente demais para comer." },
    { en: "My phone battery is almost dead.", pt: "A bateria do meu celular está quase acabando." },
    { en: "We should leave before it gets dark.", pt: "Devemos sair antes que escureça." },
    { en: "The children are playing in the yard.", pt: "As crianças estão brincando no quintal." },
    { en: "She sings beautifully at the church.", pt: "Ela canta lindamente na igreja." },
    { en: "I haven't seen him in years.", pt: "Eu não o vejo há anos." },
    { en: "The museum opens at ten in the morning.", pt: "O museu abre às dez da manhã." },
    { en: "He is very tall and strong.", pt: "Ele é muito alto e forte." },
    { en: "We are having dinner at seven.", pt: "Vamos jantar às sete." },
    { en: "The road is closed due to construction.", pt: "A estrada está fechada devido a obras." },
    { en: "My grandmother makes the best cookies.", pt: "Minha avó faz os melhores biscoitos." },
    { en: "The plane will land in twenty minutes.", pt: "O avião vai pousar em vinte minutos." },
    { en: "She is wearing a beautiful necklace.", pt: "Ela está usando um colar lindo." },
    { en: "I need a vacation soon.", pt: "Eu preciso de férias em breve." },
    { en: "The teacher explained the lesson clearly.", pt: "O professor explicou a lição claramente." },
    { en: "He forgot to turn off the lights.", pt: "Ele esqueceu de apagar as luzes." },
    { en: "The river flows through the valley.", pt: "O rio flui pelo vale." },
    { en: "We watched a documentary last night.", pt: "Assistimos a um documentário ontem à noite." },
    { en: "She is allergic to peanuts.", pt: "Ela é alérgica a amendoim." },
    { en: "The shop is having a big sale.", pt: "A loja está com uma grande promoção." },
    { en: "I can't find my glasses anywhere.", pt: "Não consigo achar meus óculos em lugar nenhum." },
    { en: "He drinks tea instead of coffee.", pt: "Ele bebe chá em vez de café." },
    { en: "The city is beautiful at night.", pt: "A cidade é linda à noite." },
    { en: "My car broke down on the highway.", pt: "Meu carro quebrou na rodovia." },
    { en: "She has a wonderful sense of humor.", pt: "Ela tem um ótimo senso de humor." },
    { en: "The restaurant serves amazing pasta.", pt: "O restaurante serve uma massa incrível." },
    { en: "We need to finish this project by Friday.", pt: "Precisamos terminar este projeto até sexta-feira." },
    { en: "He plays the guitar very well.", pt: "Ele toca violão muito bem." },
    { en: "The hotel room has a nice view.", pt: "O quarto do hotel tem uma vista bonita." },
    { en: "I love the smell of fresh bread.", pt: "Eu amo o cheiro de pão fresco." },
    { en: "She was late for the meeting.", pt: "Ela se atrasou para a reunião." },
    { en: "The dog barked at the mailman.", pt: "O cachorro latiu para o carteiro." },
    { en: "We need to save more money.", pt: "Precisamos economizar mais dinheiro." },
    { en: "He is studying to become an engineer.", pt: "Ele está estudando para se tornar engenheiro." },
    { en: "The sky is full of stars tonight.", pt: "O céu está cheio de estrelas esta noite." },
    { en: "My computer is running slow.", pt: "Meu computador está lento." },
    { en: "She painted the walls blue.", pt: "Ela pintou as paredes de azul." },
    { en: "The zoo has many exotic animals.", pt: "O zoológico tem muitos animais exóticos." },
    { en: "I need to call my mother tonight.", pt: "Preciso ligar para minha mãe hoje à noite." },
    { en: "He works from home three days a week.", pt: "Ele trabalha de casa três dias por semana." },
    { en: "The cookies are still in the oven.", pt: "Os biscoitos ainda estão no forno." },
    { en: "We missed the last bus home.", pt: "Perdemos o último ônibus para casa." },
    { en: "She is the smartest student in her class.", pt: "Ela é a aluna mais inteligente da classe." },
    { en: "The beach is crowded during summer.", pt: "A praia fica lotada durante o verão." },
    { en: "I love reading mystery novels.", pt: "Eu amo ler romances de mistério." },
    { en: "He apologized for being rude.", pt: "Ele pediu desculpas por ter sido grosseiro." },
    { en: "The wind is very strong today.", pt: "O vento está muito forte hoje." },
    { en: "My neighbor has three cats.", pt: "Meu vizinho tem três gatos." },
    { en: "She ordered pizza for dinner.", pt: "Ela pediu pizza para o jantar." },
    { en: "The children are afraid of the dark.", pt: "As crianças têm medo do escuro." },
    { en: "We are going camping this weekend.", pt: "Vamos acampar neste fim de semana." },
    { en: "He is an excellent chef.", pt: "Ele é um excelente chef." },
    { en: "The train station is near the airport.", pt: "A estação de trem é perto do aeroporto." },
    { en: "I enjoy walking along the beach.", pt: "Eu gosto de caminhar pela praia." },
    { en: "She has long, dark hair.", pt: "Ela tem cabelo longo e escuro." },
    { en: "The elevator is out of order.", pt: "O elevador está fora de serviço." },
    { en: "We should plant more trees.", pt: "Deveríamos plantar mais árvores." },
    { en: "He saved a child from drowning.", pt: "Ele salvou uma criança de se afogar." },
    { en: "The price of gasoline keeps rising.", pt: "O preço da gasolina continua subindo." },
    { en: "My watch stopped working yesterday.", pt: "Meu relógio parou de funcionar ontem." },
    { en: "She is fluent in Spanish and French.", pt: "Ela fala espanhol e francês fluentemente." },
    { en: "The park is beautiful in the spring.", pt: "O parque é lindo na primavera." },
    { en: "I always eat breakfast with my family.", pt: "Eu sempre tomo café da manhã com minha família." },
    { en: "He is afraid of heights.", pt: "Ele tem medo de altura." },
    { en: "The doctor prescribed some medicine.", pt: "O médico receitou um remédio." },
    { en: "We danced all night at the club.", pt: "Dançamos a noite toda no clube." },
    { en: "She bought fresh fruit at the market.", pt: "Ela comprou frutas frescas no mercado." },
    { en: "The old man tells great stories.", pt: "O velho conta ótimas histórias." },
    { en: "I prefer tea over coffee.", pt: "Eu prefiro chá a café." },
    { en: "He is coming home next month.", pt: "Ele está voltando para casa no próximo mês." },
    { en: "The kids are excited about Christmas.", pt: "As crianças estão animadas com o Natal." },
    { en: "My uncle lives in another country.", pt: "Meu tio mora em outro país." },
    { en: "She has a passion for photography.", pt: "Ela tem paixão por fotografia." },
    { en: "The bakery opens very early.", pt: "A padaria abre bem cedo." },
    { en: "I can't believe how fast time flies.", pt: "Não consigo acreditar como o tempo passa rápido." },
    { en: "He has a meeting with his boss today.", pt: "Ele tem uma reunião com o chefe hoje." },
    { en: "The flowers smell wonderful.", pt: "As flores têm um cheiro maravilhoso." },
    { en: "We need to paint the kitchen.", pt: "Precisamos pintar a cozinha." },
    { en: "She was born in a small village.", pt: "Ela nasceu em uma pequena vila." },
    { en: "The concert was absolutely amazing.", pt: "O show foi absolutamente incrível." },
    { en: "My phone is ringing in the other room.", pt: "Meu celular está tocando no outro cômodo." },
    { en: "He drinks a lot of water every day.", pt: "Ele bebe muita água todos os dias." },
    { en: "The snow is falling heavily outside.", pt: "A neve está caindo forte lá fora." },
    { en: "I have a headache since this morning.", pt: "Estou com dor de cabeça desde de manhã." },
    { en: "She loves dancing to Latin music.", pt: "Ela adora dançar música latina." },
    { en: "The baby started walking last week.", pt: "O bebê começou a andar na semana passada." },
    { en: "We visited the castle during our trip.", pt: "Visitamos o castelo durante nossa viagem." },
    { en: "He knows a lot about history.", pt: "Ele sabe muito sobre história." },
    { en: "The lake is frozen in winter.", pt: "O lago fica congelado no inverno." },
    { en: "I don't like spicy food.", pt: "Não gosto de comida picante." },
    { en: "She always helps her classmates.", pt: "Ela sempre ajuda os colegas de classe." },
    { en: "The bus driver was very friendly.", pt: "O motorista do ônibus foi muito simpático." },
    { en: "My shoes are too tight.", pt: "Meus sapatos estão muito apertados." },
    { en: "He is writing a novel about war.", pt: "Ele está escrevendo um romance sobre guerra." },
    { en: "The kids love swimming in the pool.", pt: "As crianças adoram nadar na piscina." },
    { en: "We celebrated our anniversary at a restaurant.", pt: "Comemoramos nosso aniversário em um restaurante." },
    { en: "She has beautiful blue eyes.", pt: "Ela tem lindos olhos azuis." },
    { en: "The storm lasted all night.", pt: "A tempestade durou a noite toda." },
    { en: "I need to buy a new laptop.", pt: "Preciso comprar um notebook novo." },
    { en: "He was promoted to manager last year.", pt: "Ele foi promovido a gerente no ano passado." },
    { en: "The forest is home to many animals.", pt: "A floresta é lar de muitos animais." },
    { en: "My favorite color is green.", pt: "Minha cor favorita é verde." },
    { en: "She is going back to college next year.", pt: "Ela vai voltar para a faculdade no ano que vem." },
    { en: "The clock on the wall is broken.", pt: "O relógio na parede está quebrado." },
    { en: "We need to call a plumber.", pt: "Precisamos chamar um encanador." },
    { en: "He invited us to his birthday party.", pt: "Ele nos convidou para a festa de aniversário dele." },
    { en: "The sky turned red at sunset.", pt: "O céu ficou vermelho ao pôr do sol." },
    { en: "I always carry an umbrella in my bag.", pt: "Sempre carrego um guarda-chuva na minha bolsa." },
    { en: "She is learning how to cook Italian food.", pt: "Ela está aprendendo a cozinhar comida italiana." },
    { en: "The book is on the top shelf.", pt: "O livro está na prateleira de cima." },
    { en: "We had pancakes for breakfast.", pt: "Tomamos panquecas no café da manhã." },
    { en: "He rides his bike to work every day.", pt: "Ele vai de bicicleta para o trabalho todos os dias." },
    { en: "The hotel has a swimming pool and a gym.", pt: "O hotel tem piscina e academia." },
    { en: "I'm not feeling well today.", pt: "Não estou me sentindo bem hoje." },
    { en: "She gave me a lovely present.", pt: "Ela me deu um presente lindo." },
    { en: "The streets are empty on Sundays.", pt: "As ruas ficam vazias aos domingos." },
    { en: "My grandfather fought in the war.", pt: "Meu avô lutou na guerra." },
    { en: "He has a great memory for names.", pt: "Ele tem uma ótima memória para nomes." },
    { en: "The boat sailed across the ocean.", pt: "O barco navegou pelo oceano." },
    { en: "We are expecting a baby in June.", pt: "Estamos esperando um bebê em junho." },
    { en: "She takes yoga classes twice a week.", pt: "Ela faz aulas de ioga duas vezes por semana." },
    { en: "The mechanic fixed my car quickly.", pt: "O mecânico consertou meu carro rapidamente." },
    { en: "I had a strange dream last night.", pt: "Tive um sonho estranho ontem à noite." },
    { en: "He collects old coins as a hobby.", pt: "Ele coleciona moedas antigas como hobby." },
    { en: "The garden needs water every morning.", pt: "O jardim precisa de água toda manhã." },
    { en: "My teacher recommended this book.", pt: "Minha professora recomendou este livro." },
    { en: "She has an interview tomorrow morning.", pt: "Ela tem uma entrevista amanhã de manhã." },
    { en: "The bird built a nest in the tree.", pt: "O pássaro construiu um ninho na árvore." },
    { en: "We are planning a trip to Europe.", pt: "Estamos planejando uma viagem para a Europa." },
    { en: "He never misses his favorite TV show.", pt: "Ele nunca perde seu programa de TV favorito." },
    { en: "The music was too loud last night.", pt: "A música estava alta demais ontem à noite." },
    { en: "I can hear the rain on the roof.", pt: "Consigo ouvir a chuva no telhado." },
    { en: "She is the captain of the team.", pt: "Ela é a capitã do time." },
    { en: "The wedding will be in a church.", pt: "O casamento será em uma igreja." },
    { en: "My cousin just moved to Canada.", pt: "Meu primo acabou de se mudar para o Canadá." },
    { en: "He owns a small business downtown.", pt: "Ele tem um pequeno negócio no centro." },
    { en: "The chocolate cake was incredible.", pt: "O bolo de chocolate estava incrível." },
    { en: "I wake up early on weekdays.", pt: "Acordo cedo nos dias úteis." },
    { en: "She whispered something in his ear.", pt: "Ela sussurrou algo no ouvido dele." },
    { en: "The leaves are changing color.", pt: "As folhas estão mudando de cor." },
    { en: "We bought a new TV last month.", pt: "Compramos uma TV nova no mês passado." },
    { en: "He believes in working hard.", pt: "Ele acredita em trabalhar duro." },
    { en: "The ice cream is melting fast.", pt: "O sorvete está derretendo rápido." },
    { en: "My apartment is on the fifth floor.", pt: "Meu apartamento é no quinto andar." },
    { en: "She never forgets a birthday.", pt: "Ela nunca esquece um aniversário." },
    { en: "The class was canceled due to illness.", pt: "A aula foi cancelada devido a doença." },
    { en: "I love spending time with my family.", pt: "Eu amo passar tempo com minha família." },
    { en: "He apologized for breaking the vase.", pt: "Ele pediu desculpas por quebrar o vaso." },
    { en: "The restaurant is fully booked tonight.", pt: "O restaurante está com reservas lotadas esta noite." },
    { en: "We went hiking in the mountains.", pt: "Fomos fazer trilha nas montanhas." },
    { en: "She planted roses in the backyard.", pt: "Ela plantou rosas no quintal." },
    { en: "The moon looks huge tonight.", pt: "A lua parece enorme esta noite." },
    { en: "I burned the toast this morning.", pt: "Queimei a torrada esta manhã." },
    { en: "He has a scar on his forehead.", pt: "Ele tem uma cicatriz na testa." },
    { en: "The airport is far from the city.", pt: "O aeroporto fica longe da cidade." },
    { en: "My keys are in my coat pocket.", pt: "Minhas chaves estão no bolso do meu casaco." },
    { en: "She laughed at his silly joke.", pt: "Ela riu da piada boba dele." },
    { en: "The exam was harder than I expected.", pt: "A prova foi mais difícil do que eu esperava." },
    { en: "We need to buy a new refrigerator.", pt: "Precisamos comprar uma geladeira nova." },
    { en: "He writes articles for a magazine.", pt: "Ele escreve artigos para uma revista." },
    { en: "The puppy is so cute and playful.", pt: "O filhote é tão fofo e brincalhão." },
    { en: "I forgot to charge my phone last night.", pt: "Esqueci de carregar meu celular ontem à noite." },
    { en: "She dances ballet since she was six.", pt: "Ela dança balé desde os seis anos." },
    { en: "The bridge connects the two islands.", pt: "A ponte conecta as duas ilhas." },
    { en: "My boss called me into his office.", pt: "Meu chefe me chamou para o escritório dele." },
    { en: "He caught a big fish at the lake.", pt: "Ele pegou um peixe grande no lago." },
    { en: "The dress fits her perfectly.", pt: "O vestido fica perfeito nela." },
    { en: "I drink orange juice every morning.", pt: "Tomo suco de laranja toda manhã." },
    { en: "She moved to a bigger house last year.", pt: "Ela se mudou para uma casa maior no ano passado." },
    { en: "The movie theater is sold out.", pt: "O cinema está com ingressos esgotados." },
    { en: "We should talk about this in private.", pt: "Devemos conversar sobre isso em particular." },
    { en: "He is training for a marathon.", pt: "Ele está treinando para uma maratona." },
    { en: "The stars are shining brightly.", pt: "As estrelas estão brilhando intensamente." },
    { en: "I need some advice from you.", pt: "Preciso de um conselho seu." },
    { en: "She writes emails in three languages.", pt: "Ela escreve e-mails em três idiomas." },
    { en: "The new café serves great pastries.", pt: "O café novo serve doces excelentes." },
    { en: "My laptop is almost out of storage.", pt: "Meu notebook está quase sem espaço." },
    { en: "He fixed the broken chair himself.", pt: "Ele mesmo consertou a cadeira quebrada." },
    { en: "The weekend went by too quickly.", pt: "O fim de semana passou rápido demais." },
    { en: "I haven't finished my homework yet.", pt: "Ainda não terminei minha lição de casa." },
    { en: "She fell asleep during the movie.", pt: "Ela dormiu durante o filme." },
    { en: "The dentist said I need a cavity filled.", pt: "O dentista disse que preciso obturar uma cárie." },
    { en: "We went to the farmer's market this morning.", pt: "Fomos à feira dos produtores esta manhã." },
    { en: "He speaks very softly.", pt: "Ele fala muito baixo." },
    { en: "The kitchen smells amazing.", pt: "A cozinha está com um cheiro incrível." },
    { en: "I parked my car on the second floor.", pt: "Estacionei meu carro no segundo andar." },
    { en: "She sent me a postcard from Paris.", pt: "Ela me mandou um cartão-postal de Paris." },
    { en: "The hotel offers free breakfast.", pt: "O hotel oferece café da manhã grátis." },
    { en: "My son just started kindergarten.", pt: "Meu filho acabou de começar o jardim de infância." },
    { en: "He built a treehouse for the kids.", pt: "Ele construiu uma casa na árvore para as crianças." },
    { en: "The pizza delivery was really fast.", pt: "A entrega da pizza foi bem rápida." },
    { en: "I usually go jogging in the morning.", pt: "Eu geralmente corro de manhã." },
    { en: "She adopted a stray cat last weekend.", pt: "Ela adotou um gato de rua no último fim de semana." },
    { en: "The classroom is quiet during the test.", pt: "A sala de aula fica silenciosa durante a prova." },
    { en: "We had a picnic in the park.", pt: "Fizemos um piquenique no parque." },
    { en: "He won a gold medal in swimming.", pt: "Ele ganhou uma medalha de ouro em natação." },
    { en: "The fireplace is warm and cozy.", pt: "A lareira está quente e aconchegante." },
    { en: "My daughter loves painting and drawing.", pt: "Minha filha adora pintar e desenhar." },
    { en: "She baked bread for the neighbors.", pt: "Ela fez pão para os vizinhos." },
    { en: "The mailman delivers letters every day.", pt: "O carteiro entrega cartas todos os dias." },
    { en: "I want to learn how to surf.", pt: "Quero aprender a surfar." },
    { en: "He proposed to her on the beach.", pt: "Ele a pediu em casamento na praia." },
    { en: "The bookstore has a huge collection.", pt: "A livraria tem uma coleção enorme." },
    { en: "My best friend moved away last year.", pt: "Minha melhor amiga se mudou no ano passado." },
    { en: "She always wears colorful scarves.", pt: "Ela sempre usa lenços coloridos." },
    { en: "The coffee machine is broken again.", pt: "A máquina de café quebrou de novo." },
    { en: "We need to clean the garage this weekend.", pt: "Precisamos limpar a garagem neste fim de semana." },
    { en: "He drives carefully in bad weather.", pt: "Ele dirige com cuidado no mau tempo." },
    { en: "The sunrise was breathtaking.", pt: "O nascer do sol foi de tirar o fôlego." },
    { en: "I need to water the plants before leaving.", pt: "Preciso regar as plantas antes de sair." },
    { en: "She wrote a letter to her grandmother.", pt: "Ela escreveu uma carta para a avó." },
    { en: "The gym opens at five in the morning.", pt: "A academia abre às cinco da manhã." },
    { en: "My neighbor plays loud music at night.", pt: "Meu vizinho toca música alta à noite." },
    { en: "He finished the book in two days.", pt: "Ele terminou o livro em dois dias." },
    { en: "The sun is really bright today.", pt: "O sol está muito forte hoje." },
    { en: "I'm excited about the concert tonight.", pt: "Estou animado com o show desta noite." },
    { en: "She walks her dog every evening.", pt: "Ela passeia com o cachorro toda noite." },
    { en: "The old photo brought back memories.", pt: "A foto antiga trouxe lembranças." },
    { en: "We are remodeling our bathroom.", pt: "Estamos reformando nosso banheiro." },
    { en: "He learned to cook from his mother.", pt: "Ele aprendeu a cozinhar com a mãe." },
    { en: "The waiter was very polite.", pt: "O garçom foi muito educado." },
    { en: "I can't wait for summer vacation.", pt: "Mal posso esperar pelas férias de verão." },
    { en: "She loves watching old black and white movies.", pt: "Ela adora assistir a filmes antigos em preto e branco." },
    { en: "The rain stopped a few minutes ago.", pt: "A chuva parou há alguns minutos." },
    { en: "My grandmother is turning eighty this year.", pt: "Minha avó vai fazer oitenta anos este ano." },
    { en: "He always parks in the wrong spot.", pt: "Ele sempre estaciona no lugar errado." },
    { en: "The ice on the pond is thick enough.", pt: "O gelo no lago está grosso o suficiente." },
    { en: "I burned my finger on the stove.", pt: "Queimei meu dedo no fogão." },
    { en: "She keeps a diary since she was ten.", pt: "Ela mantém um diário desde os dez anos." },
    { en: "The salesperson was really helpful.", pt: "O vendedor foi muito prestativo." },
    { en: "We should take the kids to the zoo.", pt: "Deveríamos levar as crianças ao zoológico." },
    { en: "He broke his leg playing soccer.", pt: "Ele quebrou a perna jogando futebol." },
    { en: "The cheese on the pizza is delicious.", pt: "O queijo na pizza está delicioso." },
    { en: "My alarm didn't go off this morning.", pt: "Meu despertador não tocou esta manhã." },
    { en: "She has a beautiful singing voice.", pt: "Ela tem uma voz linda para cantar." },
    { en: "The hurricane caused a lot of damage.", pt: "O furacão causou muitos estragos." },
    { en: "I bought tickets for the football match.", pt: "Comprei ingressos para o jogo de futebol." },
    { en: "He takes photos of nature as a hobby.", pt: "Ele tira fotos da natureza como hobby." },
    { en: "The museum has ancient artifacts.", pt: "O museu tem artefatos antigos." },
    { en: "My son is afraid of spiders.", pt: "Meu filho tem medo de aranhas." },
    { en: "She solved the puzzle in ten minutes.", pt: "Ela resolveu o quebra-cabeça em dez minutos." },
    { en: "The park has a playground for kids.", pt: "O parque tem um playground para crianças." },
    { en: "We saw fireworks on New Year's Eve.", pt: "Vimos fogos de artifício na véspera de Ano Novo." },
    { en: "He teaches math at the high school.", pt: "Ele ensina matemática no ensino médio." },
    { en: "The oranges from Florida are sweet.", pt: "As laranjas da Flórida são doces." },
    { en: "I need to replace my car tires.", pt: "Preciso trocar os pneus do meu carro." },
    { en: "She studied medicine for six years.", pt: "Ela estudou medicina por seis anos." },
    { en: "The new park opened last Saturday.", pt: "O novo parque foi inaugurado no último sábado." },
    { en: "My wife loves cooking on weekends.", pt: "Minha esposa adora cozinhar nos fins de semana." },
    { en: "He plays chess with his grandfather.", pt: "Ele joga xadrez com o avô." },
    { en: "The price of groceries keeps going up.", pt: "O preço dos mantimentos não para de subir." },
    { en: "I saw a rainbow after the rain.", pt: "Vi um arco-íris depois da chuva." },
    { en: "She is planning her daughter's birthday.", pt: "Ela está planejando o aniversário da filha." },
    { en: "The cinema has comfortable seats.", pt: "O cinema tem assentos confortáveis." },
    { en: "We visit our parents every Sunday.", pt: "Visitamos nossos pais todo domingo." },
    { en: "He wrote a song about his childhood.", pt: "Ele escreveu uma música sobre a infância." },
    { en: "The bathroom needs new tiles.", pt: "O banheiro precisa de azulejos novos." },
    { en: "I'm going to bed early tonight.", pt: "Vou dormir cedo esta noite." },
    { en: "She donated clothes to charity.", pt: "Ela doou roupas para a caridade." },
    { en: "The mountain trail was really steep.", pt: "A trilha da montanha era bem íngreme." },
    { en: "My computer needs an update.", pt: "Meu computador precisa de atualização." },
    { en: "He is known for his kindness.", pt: "Ele é conhecido pela bondade." },
    { en: "The supermarket is closed on holidays.", pt: "O supermercado fecha nos feriados." },
    { en: "I've been studying French for two years.", pt: "Estou estudando francês há dois anos." },
    { en: "She wore a red dress to the gala.", pt: "Ela usou um vestido vermelho no evento de gala." },
    { en: "The dog chased the cat around the yard.", pt: "O cachorro perseguiu o gato pelo quintal." },
    { en: "We had coffee on the balcony.", pt: "Tomamos café na varanda." },
    { en: "He repaired the leaky faucet.", pt: "Ele consertou a torneira que vazava." },
    { en: "The bakery sells fresh croissants every morning.", pt: "A padaria vende croissants frescos toda manhã." },
    { en: "I lost my glasses at the restaurant.", pt: "Perdi meus óculos no restaurante." },
    { en: "She takes piano lessons on Thursdays.", pt: "Ela tem aulas de piano às quintas-feiras." },
    { en: "The fireworks lit up the night sky.", pt: "Os fogos iluminaram o céu noturno." },
    { en: "My job requires a lot of traveling.", pt: "Meu trabalho exige muitas viagens." },
    { en: "He drinks three cups of coffee a day.", pt: "Ele toma três xícaras de café por dia." },
    { en: "The garage door won't open.", pt: "A porta da garagem não quer abrir." },
    { en: "I slept for ten hours last night.", pt: "Dormi dez horas ontem à noite." },
    { en: "She has a passion for old movies.", pt: "Ela tem paixão por filmes antigos." },
    { en: "The butter melted in the hot pan.", pt: "A manteiga derreteu na panela quente." },
    { en: "We bought a beach house last summer.", pt: "Compramos uma casa de praia no verão passado." },
    { en: "He is a very talented artist.", pt: "Ele é um artista muito talentoso." },
    { en: "The puppy chewed up my shoe.", pt: "O filhote mastigou meu sapato." },
    { en: "I always carry a notebook with me.", pt: "Sempre levo um caderno comigo." },
    { en: "She finished her degree with honors.", pt: "Ela terminou o curso com honras." },
    { en: "The fish tank needs to be cleaned.", pt: "O aquário precisa ser limpo." },
    { en: "My best friend got married last weekend.", pt: "Meu melhor amigo se casou no último fim de semana." },
    { en: "He spent the afternoon in the library.", pt: "Ele passou a tarde na biblioteca." },
    { en: "The old bridge is still standing.", pt: "A ponte antiga ainda está de pé." },
    { en: "I don't like horror movies.", pt: "Não gosto de filmes de terror." },
    { en: "She learned to ride a bike at five.", pt: "Ela aprendeu a andar de bicicleta aos cinco anos." },
    { en: "The traffic is terrible this morning.", pt: "O trânsito está terrível esta manhã." },
    { en: "We watched the game together.", pt: "Assistimos ao jogo juntos." },
    { en: "He travels to Japan every year.", pt: "Ele viaja para o Japão todo ano." },
    { en: "The stew was cooking for hours.", pt: "O ensopado cozinhou por horas." },
    { en: "I'm trying to eat healthier food.", pt: "Estou tentando comer comida mais saudável." },
    { en: "She paints watercolors in her studio.", pt: "Ela pinta aquarelas no ateliê." },
    { en: "The shop sells handmade jewelry.", pt: "A loja vende joias feitas à mão." },
    { en: "My brother is taller than me now.", pt: "Meu irmão agora é mais alto do que eu." },
    { en: "He forgot our anniversary this year.", pt: "Ele esqueceu do nosso aniversário este ano." },
    { en: "The snow melted by noon.", pt: "A neve derreteu até o meio-dia." },
    { en: "I need to schedule a dentist appointment.", pt: "Preciso marcar uma consulta no dentista." },
    { en: "She grew tomatoes in her backyard.", pt: "Ela plantou tomates no quintal." },
    { en: "The waves are perfect for surfing today.", pt: "As ondas estão perfeitas para surfar hoje." },
    { en: "We listened to the radio during the trip.", pt: "Ouvimos rádio durante a viagem." },
    { en: "He volunteers at the local hospital.", pt: "Ele é voluntário no hospital local." },
    { en: "The weather report predicts rain tomorrow.", pt: "A previsão do tempo indica chuva amanhã." },
    { en: "I always carry cash for emergencies.", pt: "Sempre carrego dinheiro para emergências." },
    { en: "She invited everyone to the barbecue.", pt: "Ela convidou todo mundo para o churrasco." },
    { en: "The candles flickered in the wind.", pt: "As velas tremularam com o vento." },
    { en: "My son loves dinosaurs and space.", pt: "Meu filho adora dinossauros e espaço." },
    { en: "He made a delicious apple pie.", pt: "Ele fez uma torta de maçã deliciosa." },
    { en: "The meeting was postponed to next week.", pt: "A reunião foi adiada para a próxima semana." },
    { en: "I like the quiet of the countryside.", pt: "Eu gosto do silêncio do campo." },
    { en: "She has been my friend for years.", pt: "Ela tem sido minha amiga há anos." },
    { en: "The pharmacy is on the corner.", pt: "A farmácia fica na esquina." },
    { en: "We ordered Chinese food for dinner.", pt: "Pedimos comida chinesa para o jantar." },
    { en: "He got a new job in the city.", pt: "Ele conseguiu um emprego novo na cidade." },
    { en: "The butterflies were flying in the garden.", pt: "As borboletas voavam no jardim." },
    { en: "I prefer watching movies at home.", pt: "Prefiro assistir a filmes em casa." },
    { en: "She writes articles about travel.", pt: "Ela escreve artigos sobre viagens." },
    { en: "The thunder scared the children.", pt: "O trovão assustou as crianças." },
    { en: "My father used to be a pilot.", pt: "Meu pai era piloto." },
    { en: "He has a twin brother named Paul.", pt: "Ele tem um irmão gêmeo chamado Paul." },
    { en: "The cake was decorated with fresh fruit.", pt: "O bolo foi decorado com frutas frescas." },
    { en: "I don't watch television anymore.", pt: "Não assisto mais à televisão." },
    { en: "She bought a ticket to New York.", pt: "Ela comprou uma passagem para Nova York." },
    { en: "The shoes are too expensive for me.", pt: "Os sapatos estão caros demais para mim." },
    { en: "We need to refill the gas tank.", pt: "Precisamos reabastecer o tanque de gasolina." },
    { en: "He reads the newspaper every morning.", pt: "Ele lê o jornal toda manhã." },
    { en: "The classroom was full of excited students.", pt: "A sala de aula estava cheia de alunos animados." },
    { en: "I always lock the door before sleeping.", pt: "Sempre tranco a porta antes de dormir." },
    { en: "She called an ambulance immediately.", pt: "Ela chamou uma ambulância imediatamente." },
    { en: "The lighthouse guides ships at night.", pt: "O farol guia os navios à noite." },
    { en: "My uncle owns a farm in the countryside.", pt: "Meu tio tem uma fazenda no interior." },
    { en: "He drove all night to get home.", pt: "Ele dirigiu a noite toda para chegar em casa." },
    { en: "The smell of coffee fills the kitchen.", pt: "O cheiro de café toma conta da cozinha." },
    { en: "I don't want to be late again.", pt: "Não quero me atrasar de novo." },
    { en: "She was elected class president.", pt: "Ela foi eleita presidente da turma." },
    { en: "The forest fire spread quickly.", pt: "O incêndio na floresta se espalhou rápido." },
    { en: "We are saving money for a new car.", pt: "Estamos economizando para um carro novo." },
    { en: "He gave me a bouquet of roses.", pt: "Ele me deu um buquê de rosas." },
    { en: "The taxi driver knew a shortcut.", pt: "O taxista conhecia um atalho." },
    { en: "I need to exercise more regularly.", pt: "Preciso me exercitar com mais regularidade." },
    { en: "She remembered to bring her umbrella.", pt: "Ela lembrou de trazer o guarda-chuva." },
    { en: "The lemonade is very refreshing.", pt: "A limonada está bem refrescante." },
    { en: "My friend opened a new bakery.", pt: "Meu amigo abriu uma padaria nova." },
    { en: "He has a meeting every Monday morning.", pt: "Ele tem uma reunião toda segunda de manhã." },
    { en: "The students love their new teacher.", pt: "Os alunos adoram o novo professor." },
    { en: "I spilled coffee on my shirt.", pt: "Derramei café na minha camisa." },
    { en: "She baked cookies for the children.", pt: "Ela fez biscoitos para as crianças." },
    { en: "The birds wake me up every morning.", pt: "Os pássaros me acordam toda manhã." },
    { en: "We took a boat ride on the lake.", pt: "Demos um passeio de barco no lago." },
    { en: "He plays the violin beautifully.", pt: "Ele toca violino lindamente." },
    { en: "The zoo is closed for maintenance.", pt: "O zoológico está fechado para manutenção." },
    { en: "I always have breakfast at eight.", pt: "Sempre tomo café da manhã às oito." },
    { en: "She fell in love with the city.", pt: "Ela se apaixonou pela cidade." },
    { en: "The factory produces cars and trucks.", pt: "A fábrica produz carros e caminhões." },
    { en: "My sister got a promotion last month.", pt: "Minha irmã foi promovida no mês passado." },
    { en: "He always helps his elderly neighbor.", pt: "Ele sempre ajuda o vizinho idoso." },
    { en: "The sandwich was enormous and tasty.", pt: "O sanduíche era enorme e gostoso." },
    { en: "I enjoy hiking on the weekends.", pt: "Eu gosto de fazer trilha nos fins de semana." },
    { en: "She watched the children play.", pt: "Ela observou as crianças brincarem." },
    { en: "The boat arrived at the harbor.", pt: "O barco chegou ao porto." },
    { en: "We are going to the movies tonight.", pt: "Vamos ao cinema esta noite." },
    { en: "He cleaned the whole house by himself.", pt: "Ele limpou a casa inteira sozinho." },
    { en: "The baby laughed at the puppet show.", pt: "O bebê riu do show de fantoches." },
    { en: "I live near a big supermarket.", pt: "Moro perto de um supermercado grande." },
    { en: "She knitted a scarf for her son.", pt: "Ela tricotou um cachecol para o filho." },
    { en: "The printer is out of ink again.", pt: "A impressora está sem tinta de novo." },
    { en: "My dad taught me how to drive.", pt: "Meu pai me ensinou a dirigir." },
    { en: "He always carries a book in his bag.", pt: "Ele sempre carrega um livro na bolsa." },
    { en: "The smell of roses filled the room.", pt: "O cheiro de rosas tomou conta do quarto." },
    { en: "I need to pay my bills this week.", pt: "Preciso pagar minhas contas esta semana." },
    { en: "She traveled alone to Thailand.", pt: "Ela viajou sozinha para a Tailândia." },
    { en: "The firefighters arrived quickly.", pt: "Os bombeiros chegaram rapidamente." },
    { en: "We shared a pizza at lunch.", pt: "Dividimos uma pizza no almoço." },
    { en: "He loves telling funny stories.", pt: "Ele adora contar histórias engraçadas." },
    { en: "The pond was full of ducks.", pt: "O laguinho estava cheio de patos." },
    { en: "I finished the puzzle in one hour.", pt: "Terminei o quebra-cabeça em uma hora." },
    { en: "She has a cat named Whiskers.", pt: "Ela tem um gato chamado Whiskers." },
    { en: "The ice cream truck plays music.", pt: "O carro do sorvete toca música." },
    { en: "My husband cooks on Sundays.", pt: "Meu marido cozinha aos domingos." },
    { en: "He passed the driving test on the first try.", pt: "Ele passou no teste de direção na primeira tentativa." },
    { en: "The wind blew the papers off the desk.", pt: "O vento levou os papéis da mesa." },
    { en: "I forgot my umbrella at the café.", pt: "Esqueci meu guarda-chuva no café." },
    { en: "She took a deep breath before speaking.", pt: "Ela respirou fundo antes de falar." },
    { en: "The clock is ticking very loudly.", pt: "O relógio está fazendo tique-taque bem alto." },
    { en: "We are having a family reunion.", pt: "Vamos ter uma reunião de família." },
    { en: "He reads bedtime stories to his kids.", pt: "Ele lê histórias para os filhos antes de dormir." },
    { en: "The mountain was covered in snow.", pt: "A montanha estava coberta de neve." },
    { en: "I prefer cold weather over hot.", pt: "Prefiro clima frio a quente." },
    { en: "She gave a wonderful speech.", pt: "Ela fez um discurso maravilhoso." },
    { en: "The hotel staff was very friendly.", pt: "A equipe do hotel foi muito simpática." },
    { en: "My cousin is studying law.", pt: "Minha prima está estudando direito." },
    { en: "He has a great collection of records.", pt: "Ele tem uma ótima coleção de discos." },
    { en: "The steak was cooked to perfection.", pt: "O bife foi feito no ponto perfeito." },
    { en: "I take vitamins every morning.", pt: "Tomo vitaminas toda manhã." },
    { en: "She volunteers at the animal shelter.", pt: "Ela é voluntária no abrigo de animais." },
    { en: "The parade lasted two hours.", pt: "O desfile durou duas horas." },
    { en: "We camped by the river last night.", pt: "Acampamos perto do rio ontem à noite." },
    { en: "He drinks tea with lemon and honey.", pt: "Ele toma chá com limão e mel." },
    { en: "The library has comfortable chairs.", pt: "A biblioteca tem cadeiras confortáveis." },
    { en: "I missed my flight yesterday.", pt: "Perdi meu voo ontem." },
    { en: "She designed her own wedding dress.", pt: "Ela desenhou o próprio vestido de noiva." },
    { en: "The train was delayed for an hour.", pt: "O trem atrasou uma hora." },
    { en: "My children love bedtime stories.", pt: "Meus filhos adoram histórias antes de dormir." },
    { en: "He is saving to buy a motorcycle.", pt: "Ele está economizando para comprar uma moto." },
    { en: "The lemon tree is full of fruit.", pt: "O pé de limão está cheio de frutos." },
    { en: "I took the dog for a long walk.", pt: "Levei o cachorro para um passeio longo." },
    { en: "She practices meditation every night.", pt: "Ela medita toda noite." },
    { en: "The bakery is famous for its pies.", pt: "A padaria é famosa pelas tortas." },
    { en: "We should recycle more at home.", pt: "Deveríamos reciclar mais em casa." },
    { en: "He graduated from college last May.", pt: "Ele se formou na faculdade em maio passado." },
    { en: "The moon disappeared behind the clouds.", pt: "A lua desapareceu atrás das nuvens." },
    { en: "I bought a new pair of boots.", pt: "Comprei um par de botas novo." },
    { en: "She is running late for the train.", pt: "Ela está atrasada para o trem." },
    { en: "The garden is full of butterflies.", pt: "O jardim está cheio de borboletas." },
    { en: "My grandfather loves to garden.", pt: "Meu avô adora cuidar do jardim." },
    { en: "He forgot to pay the electricity bill.", pt: "Ele esqueceu de pagar a conta de luz." },
    { en: "The hot air balloon rose slowly.", pt: "O balão de ar quente subiu devagar." },
    { en: "I admire her patience and kindness.", pt: "Admiro a paciência e a bondade dela." },
    { en: "She speaks both Spanish and Portuguese.", pt: "Ela fala espanhol e português." },
    { en: "The farmer works from dawn to dusk.", pt: "O fazendeiro trabalha do amanhecer ao anoitecer." },
    { en: "We had ice cream after dinner.", pt: "Tomamos sorvete depois do jantar." },
    { en: "He sings in the church choir.", pt: "Ele canta no coral da igreja." },
    { en: "The bookshop has a small café inside.", pt: "A livraria tem um pequeno café dentro." },
    { en: "I love the sound of rain at night.", pt: "Amo o som da chuva à noite." },
    { en: "She taught me how to make pasta.", pt: "Ela me ensinou a fazer massa." },
    { en: "The glass fell and shattered on the floor.", pt: "O copo caiu e se espatifou no chão." },
    { en: "My roommate plays video games all day.", pt: "Meu colega de quarto joga videogame o dia todo." },
    { en: "He was late because of the traffic.", pt: "Ele se atrasou por causa do trânsito." },
    { en: "The clouds are moving across the sky.", pt: "As nuvens estão se movendo pelo céu." },
    { en: "I would love to visit Italy someday.", pt: "Adoraria visitar a Itália um dia." },
    { en: "She loves romantic novels.", pt: "Ela adora romances." },
    { en: "The cat jumped onto the counter.", pt: "O gato pulou no balcão." },
    { en: "We went to a jazz concert last night.", pt: "Fomos a um show de jazz ontem à noite." },
    { en: "He lives in a quiet neighborhood.", pt: "Ele mora em um bairro tranquilo." },
    { en: "The farmer grows organic vegetables.", pt: "O fazendeiro cultiva vegetais orgânicos." },
    { en: "I need to renew my passport.", pt: "Preciso renovar meu passaporte." },
    { en: "She sent flowers to her mother.", pt: "Ela mandou flores para a mãe." },
    { en: "The bridge was built a century ago.", pt: "A ponte foi construída há um século." },
    { en: "My boss gave me a bonus this year.", pt: "Meu chefe me deu um bônus este ano." },
    { en: "He practices yoga every morning.", pt: "Ele pratica ioga toda manhã." },
    { en: "The kids built a snowman in the yard.", pt: "As crianças fizeram um boneco de neve no quintal." },
    { en: "I love eating fresh seafood.", pt: "Amo comer frutos do mar frescos." },
    { en: "She has a degree in biology.", pt: "Ela é formada em biologia." },
    { en: "The balloon floated up into the sky.", pt: "O balão subiu flutuando pelo céu." },
    { en: "We need to leave in ten minutes.", pt: "Precisamos sair em dez minutos." },
    { en: "He is a respected judge in the city.", pt: "Ele é um juiz respeitado na cidade." },
    { en: "The waiter brought us the wrong order.", pt: "O garçom trouxe o pedido errado." },
    { en: "I like long walks on the beach.", pt: "Gosto de longas caminhadas na praia." },
    { en: "She lost her job during the pandemic.", pt: "Ela perdeu o emprego durante a pandemia." },
    { en: "The orchestra played beautifully.", pt: "A orquestra tocou lindamente." },
    { en: "My brother collects vintage cars.", pt: "Meu irmão coleciona carros antigos." },
    { en: "He is afraid to swim in the ocean.", pt: "Ele tem medo de nadar no oceano." },
    { en: "The new phone has an excellent camera.", pt: "O celular novo tem uma ótima câmera." },
    { en: "I need to get a haircut tomorrow.", pt: "Preciso cortar o cabelo amanhã." },
    { en: "She finished the marathon in four hours.", pt: "Ela terminou a maratona em quatro horas." },
    { en: "The garage is full of old boxes.", pt: "A garagem está cheia de caixas velhas." },
    { en: "We played cards all evening.", pt: "Jogamos cartas a noite toda." },
    { en: "He works in a bank downtown.", pt: "Ele trabalha em um banco no centro." },
    { en: "The river was too cold to swim in.", pt: "O rio estava frio demais para nadar." },
    { en: "I'm thinking about buying a new car.", pt: "Estou pensando em comprar um carro novo." },
    { en: "She has a beautiful smile.", pt: "Ela tem um sorriso lindo." },
    { en: "The barn is behind the farmhouse.", pt: "O celeiro fica atrás da casa de fazenda." },
    { en: "My neighbor is very noisy.", pt: "Meu vizinho é muito barulhento." },
    { en: "He writes code for a living.", pt: "Ele escreve código como profissão." },
    { en: "The mountains were covered in fog.", pt: "As montanhas estavam cobertas de neblina." },
    { en: "I love fresh flowers in my house.", pt: "Adoro flores frescas em casa." },
    { en: "She fixed the computer by herself.", pt: "Ela consertou o computador sozinha." },
    { en: "The chocolate was too sweet for me.", pt: "O chocolate estava doce demais para mim." },
    { en: "We are going skiing next weekend.", pt: "Vamos esquiar no próximo fim de semana." },
    { en: "He studies history at the university.", pt: "Ele estuda história na universidade." },
    { en: "The grandmother hugged her grandchild.", pt: "A avó abraçou o neto." },
    { en: "I need more space in my closet.", pt: "Preciso de mais espaço no armário." },
    { en: "She loves painting landscapes.", pt: "Ela adora pintar paisagens." },
    { en: "The stadium was packed with fans.", pt: "O estádio estava lotado de torcedores." },
    { en: "My phone fell into the water.", pt: "Meu celular caiu na água." },
    { en: "He wore a black suit to the funeral.", pt: "Ele usou um terno preto no funeral." },
    { en: "The coffee is always strong in Italy.", pt: "O café é sempre forte na Itália." },
    { en: "I prefer the mountains to the beach.", pt: "Prefiro montanhas a praias." },
    { en: "She makes her own jewelry.", pt: "Ela faz as próprias joias." },
    { en: "The ceiling fan is spinning slowly.", pt: "O ventilador de teto está girando devagar." },
    { en: "We took a selfie at the top of the hill.", pt: "Tiramos uma selfie no topo do morro." },
    { en: "He reads everything about history.", pt: "Ele lê tudo sobre história." },
    { en: "The kids helped set the table.", pt: "As crianças ajudaram a pôr a mesa." },
    { en: "I want to learn how to play guitar.", pt: "Quero aprender a tocar violão." },
    { en: "She always brings flowers when visiting.", pt: "Ela sempre leva flores quando visita alguém." },
    { en: "The new mall has many stores.", pt: "O novo shopping tem muitas lojas." },
    { en: "My car needs an oil change.", pt: "Meu carro precisa de troca de óleo." },
    { en: "He proposed at the top of the Eiffel Tower.", pt: "Ele pediu em casamento no topo da Torre Eiffel." },
    { en: "The window was left open all night.", pt: "A janela ficou aberta a noite toda." },
    { en: "I love spicy Mexican food.", pt: "Amo comida mexicana apimentada." },
    { en: "She keeps forgetting her password.", pt: "Ela vive esquecendo a senha." },
    { en: "The old man walked with a cane.", pt: "O velho andava com bengala." },
    { en: "We drank wine on the terrace.", pt: "Tomamos vinho no terraço." },
    { en: "He is good at solving math problems.", pt: "Ele é bom em resolver problemas de matemática." },
    { en: "The storm knocked down the power lines.", pt: "A tempestade derrubou os postes de luz." },
    { en: "I want to adopt a puppy from the shelter.", pt: "Quero adotar um filhote do abrigo." },
    { en: "She listens to podcasts while driving.", pt: "Ela ouve podcasts enquanto dirige." },
    { en: "The flowers wilted in the heat.", pt: "As flores murcharam no calor." },
    { en: "My dad told me the story.", pt: "Meu pai me contou a história." },
    { en: "He donates to charity every month.", pt: "Ele doa para a caridade todo mês." },
    { en: "The waves crashed against the rocks.", pt: "As ondas se chocavam contra as rochas." },
    { en: "I enjoy quiet evenings at home.", pt: "Eu gosto de noites tranquilas em casa." },
    { en: "She dreams of traveling to space.", pt: "Ela sonha em viajar para o espaço." },
    { en: "The printer is working again.", pt: "A impressora está funcionando de novo." },
    { en: "We spent the night in a cozy cabin.", pt: "Passamos a noite em uma cabana aconchegante." },
    { en: "He is a very patient teacher.", pt: "Ele é um professor muito paciente." },
    { en: "The bread smelled freshly baked.", pt: "O pão tinha cheiro de recém-assado." },
    { en: "I have to wake up early tomorrow.", pt: "Tenho que acordar cedo amanhã." },
    { en: "She reads the Bible every night.", pt: "Ela lê a Bíblia toda noite." },
    { en: "The plumber fixed the broken pipe.", pt: "O encanador consertou o cano quebrado." },
    { en: "My friends threw me a surprise party.", pt: "Meus amigos fizeram uma festa surpresa para mim." },
    { en: "He runs every morning before work.", pt: "Ele corre toda manhã antes do trabalho." },
    { en: "The chicken soup tastes like my grandmother's.", pt: "A canja tem gosto da canja da minha avó." },
    { en: "I need to update my resume.", pt: "Preciso atualizar meu currículo." },
    { en: "She was fired for being late.", pt: "Ela foi demitida por se atrasar." },
    { en: "The pencil rolled off the desk.", pt: "O lápis rolou da mesa." },
    { en: "We watched fireworks on the beach.", pt: "Assistimos a fogos na praia." },
    { en: "He is a kind and thoughtful person.", pt: "Ele é uma pessoa gentil e atenciosa." },
    { en: "The castle is over six hundred years old.", pt: "O castelo tem mais de seiscentos anos." },
    { en: "I love the quiet of early mornings.", pt: "Amo a tranquilidade do início da manhã." },
    { en: "She takes the subway to work.", pt: "Ela pega o metrô para o trabalho." },
    { en: "The vegetables are fresh from the garden.", pt: "Os vegetais são fresquinhos da horta." },
    { en: "My dog loves to chase squirrels.", pt: "Meu cachorro adora correr atrás de esquilos." },
    { en: "He is going to propose tonight.", pt: "Ele vai fazer o pedido de casamento esta noite." },
    { en: "The nurse was very kind.", pt: "A enfermeira foi muito gentil." },
    { en: "I hate washing the dishes.", pt: "Eu odeio lavar a louça." },
    { en: "She hosts a radio show every Saturday.", pt: "Ela apresenta um programa de rádio todo sábado." },
    { en: "The kids painted the fence white.", pt: "As crianças pintaram a cerca de branco." },
    { en: "We had dinner on the rooftop.", pt: "Jantamos no terraço." },
    { en: "He made a promise he couldn't keep.", pt: "Ele fez uma promessa que não pôde cumprir." },
    { en: "The ocean breeze feels wonderful.", pt: "A brisa do mar é maravilhosa." },
    { en: "I accidentally deleted the file.", pt: "Apaguei o arquivo sem querer." },
    { en: "She always orders the same dish.", pt: "Ela sempre pede o mesmo prato." },
    { en: "The guitar is in the corner of the room.", pt: "O violão está no canto do quarto." },
    { en: "My grandmother knit me a sweater.", pt: "Minha avó me tricotou um suéter." },
    { en: "He owns a beautiful old clock.", pt: "Ele tem um relógio antigo lindo." },
    { en: "The night sky was full of stars.", pt: "O céu noturno estava cheio de estrelas." },
    { en: "I'm saving money for a trip to Japan.", pt: "Estou economizando para uma viagem ao Japão." },
    { en: "She cooks dinner every evening.", pt: "Ela faz o jantar toda noite." },
    { en: "The taxi smelled like cigarettes.", pt: "O táxi cheirava a cigarro." },
    { en: "We should visit the art gallery.", pt: "Deveríamos visitar a galeria de arte." },
    { en: "He forgot to bring his lunch.", pt: "Ele esqueceu de trazer o almoço." },
    { en: "The pond froze over in winter.", pt: "O laguinho congelou no inverno." },
    { en: "I'm reading a book about ancient Egypt.", pt: "Estou lendo um livro sobre o antigo Egito." },
    { en: "She is a very talented dancer.", pt: "Ela é uma dançarina muito talentosa." },
    { en: "The museum has free entry on Sundays.", pt: "O museu tem entrada gratuita aos domingos." },
    { en: "My cat sleeps on my laptop.", pt: "Meu gato dorme em cima do meu notebook." },
    { en: "He spent his savings on a guitar.", pt: "Ele gastou as economias num violão." },
    { en: "The students protested outside the school.", pt: "Os alunos protestaram em frente à escola." },
    { en: "I walk my dog twice a day.", pt: "Passeio com meu cachorro duas vezes por dia." },
    { en: "She opened a restaurant downtown.", pt: "Ela abriu um restaurante no centro." },
    { en: "The window has a beautiful view.", pt: "A janela tem uma vista linda." },
    { en: "We are planning a surprise for him.", pt: "Estamos planejando uma surpresa para ele." },
    { en: "He drives a vintage motorcycle.", pt: "Ele dirige uma motocicleta antiga." },
    { en: "The old photograph made her cry.", pt: "A foto antiga a fez chorar." },
    { en: "I want to buy a house by the sea.", pt: "Quero comprar uma casa à beira-mar." },
    { en: "She always listens to my problems.", pt: "Ela sempre escuta meus problemas." },
    { en: "The sun set behind the mountains.", pt: "O sol se pôs atrás das montanhas." },
    { en: "My cousin is getting married soon.", pt: "Minha prima vai se casar em breve." },
    { en: "He plays the drums in a band.", pt: "Ele toca bateria em uma banda." },
    { en: "The streetlights turned on at dusk.", pt: "Os postes se acenderam ao anoitecer." },
    { en: "I want to try a new hobby.", pt: "Quero tentar um hobby novo." },
    { en: "She made coffee for everyone in the office.", pt: "Ela fez café para todo mundo no escritório." },
    { en: "The dog wagged its tail happily.", pt: "O cachorro abanou o rabo alegremente." },
    { en: "We watched the sunrise from the hill.", pt: "Vimos o nascer do sol do morro." },
    { en: "He lives with his parents.", pt: "Ele mora com os pais." },
    { en: "The classroom window was broken.", pt: "A janela da sala de aula estava quebrada." },
    { en: "I don't eat meat anymore.", pt: "Não como mais carne." },
    { en: "She gave birth to twins last year.", pt: "Ela deu à luz gêmeos no ano passado." },
    { en: "The library has a quiet reading room.", pt: "A biblioteca tem uma sala de leitura silenciosa." },
    { en: "My son wants to be an astronaut.", pt: "Meu filho quer ser astronauta." },
    { en: "He always tells the truth.", pt: "Ele sempre diz a verdade." },
    { en: "The rainbow appeared after the storm.", pt: "O arco-íris apareceu depois da tempestade." },
    { en: "I need to buy a birthday gift.", pt: "Preciso comprar um presente de aniversário." },
    { en: "She lives in an old stone house.", pt: "Ela mora em uma casa antiga de pedra." },
    { en: "The flight was delayed due to weather.", pt: "O voo atrasou por causa do tempo." },
    { en: "We walked through the old town.", pt: "Caminhamos pela cidade antiga." },
    { en: "He dropped his phone in the pool.", pt: "Ele deixou cair o celular na piscina." },
    { en: "The swimming pool is closed for repairs.", pt: "A piscina está fechada para reparos." },
    { en: "I need to return these books to the library.", pt: "Preciso devolver esses livros à biblioteca." },
    { en: "She went to the gym after work.", pt: "Ela foi à academia depois do trabalho." },
    { en: "The lightning lit up the sky.", pt: "O relâmpago iluminou o céu." },
    { en: "My little brother loves cartoons.", pt: "Meu irmãozinho adora desenhos animados." },
    { en: "He plays tennis every Saturday morning.", pt: "Ele joga tênis todo sábado de manhã." }
  ];

  const indiceAleatorio = Math.floor(Math.random() * frases.length);
  return frases[indiceAleatorio];
}

export function getFraseAleatoriaUmIdioma() {
  const frase = getFraseAleatoria();
  const idioma = Math.random() < 0.5 ? 'en' : 'pt';
  return {
    texto: frase[idioma],
    idioma: idioma
  };
}